/// Table technique regroupant toutes les mesures du modèle (aucune donnée).
table _Mesures
	lineageTag: a2e58751-5502-46c6-95f8-1dc665aa31ec

	/// Nombre de commandes (grain fact_commandes).
	measure 'Nb Commandes' = COUNTROWS(fact_commandes)
		formatString: #,##0
		lineageTag: 2a5e017f-d3b9-4fc8-bc92-1f1b103b9945

	/// Nombre de colis (grain fact_transport).
	measure 'Nb Colis' = COUNTROWS(fact_transport)
		formatString: #,##0
		lineageTag: 7f531780-6ee8-4ea5-a56f-17fb98fca792

	/// Colis dont le coût provient d'une facture Colissimo/Chronopost rapprochée.
	measure 'Nb Colis (coût réel)' = CALCULATE([Nb Colis], fact_transport[source_cout] = "facture_rapprochee")
		formatString: #,##0
		lineageTag: b1c2d3e4-f5a6-4b7c-8d9e-0f1a2b3c4d5e

	/// Colis dont le coût provient du backend (shipping_cost_eur) sans facture transporteur.
	measure 'Nb Colis (coût estimé)' = CALCULATE([Nb Colis], fact_transport[source_cout] = "backend_seul")
		formatString: #,##0
		lineageTag: c2d3e4f5-a6b7-4c8d-9e0f-1a2b3c4d5e6f

	/// Colis sans facture ni coût backend renseigné (visibles en volume, exclus du coût).
	measure 'Nb Colis (coût non disponible)' = CALCULATE([Nb Colis], fact_transport[source_cout] = "aucun")
		formatString: #,##0
		lineageTag: d3e4f5a6-b7c8-4d9e-0f1a-2b3c4d5e6f7a

	/// Nombre de lignes de facture transporteur (Colissimo + Chronopost).
	measure 'Nb Colis Facturés' = COUNTROWS(fact_factures_transport)
		formatString: #,##0
		lineageTag: e8d8c253-ebbc-411c-a7c6-70f93389efb0

	/// Fix Bloc2 — grain passé de groupe/titre à article physique le 15/07/2026.
	/// Ancienne mesure basée sur SUM(quantity_groupe) déduplicable en contrôle si besoin,
	/// voir [Nb Articles (contrôle grain groupe)].
	measure 'Nb Articles' = COUNTROWS(fact_lignes)
		formatString: #,##0
		lineageTag: 58c14c19-db5c-4284-aecc-b00079f4d9b6

	/// Contrôle Bloc2 — recalcule l'ancien total par somme des quantity_groupe distincts par groupe.
	measure 'Nb Articles (contrôle grain groupe)' =
			SUMX(
				VALUES(fact_lignes[item_group_id]),
				CALCULATE(MAX(fact_lignes[quantity_groupe]))
			)
		formatString: #,##0
		lineageTag: e1f2a3b4-c5d6-4789-a012-3456789abcde

	/// Granularité Bloc2 — articles dont internal_state = CANCELLED (pas la logique de marge Bloc 3).
	measure 'Nb Articles Annulés' = CALCULATE([Nb Articles], fact_lignes[internal_state] = "CANCELLED")
		formatString: #,##0
		lineageTag: f2a3b4c5-d6e7-4890-b123-456789abcdef

	/// Bloc3 — CA HT au grain article, zéro sur les lignes annulées (avant ET après expédition).
	/// Remplace fact_commandes[ca_ht] pour la logique de marge Bloc 3 : zéro appliqué au grain
	/// article, pas commande, pour gérer les annulations partielles (~8 900 commandes, audit 15/07/2026).
	measure 'CA Total HT (grain article, ajusté annulation)' =
			SUMX(
				fact_lignes,
				IF(
					fact_lignes[statut_annulation_ligne] = "NON_ANNULE",
					fact_lignes[customer_price_per_item_eur],
					0
				)
			)
		formatString: #,##0.00 €
		lineageTag: a3b4c5d6-e7f8-4901-c234-567890abcdef

	/// Bloc3 — coût d'achat au grain article. Conservé dans TOUS les cas d'annulation
	/// (avant ET après expédition, décision Marc) — contrôle vs [Coût Achat Total] (grain commande).
	measure 'Coût Achat Total (grain article)' = SUM(fact_lignes[product_cost_eur])
		formatString: #,##0.00 €
		lineageTag: b4c5d6e7-f8a9-4012-d345-678901bcdef0

	/// Bloc3 — articles annulés avant expédition (proxy package_id null).
	measure 'Nb Articles Annulés Avant Expédition' =
			CALCULATE([Nb Articles], fact_lignes[statut_annulation_ligne] = "ANNULE_AVANT_EXPEDITION")
		formatString: #,##0
		lineageTag: c5d6e7f8-a9b0-4123-e456-789012cdef01

	/// Bloc3 — articles annulés après expédition (proxy package_id non-null).
	measure 'Nb Articles Annulés Après Expédition' =
			CALCULATE([Nb Articles], fact_lignes[statut_annulation_ligne] = "ANNULE_APRES_EXPEDITION")
		formatString: #,##0
		lineageTag: d6e7f8a9-b0c1-4234-f567-890123def012

	/// Bloc3 — marge brute provisoire au grain article (contrôle/comparaison uniquement).
	/// Ne remplace pas [Marge Brute] tant que les Blocs 5 (returns/generic costs) ne sont pas
	/// intégrés au même grain. Ne pas publier dans le rapport final sans validation Marc.
	measure 'Marge Brute (grain article, prov.)' =
			[CA Total HT (grain article, ajusté annulation)] - [Coût Achat Total (grain article)]
		formatString: #,##0.00 €
		lineageTag: e7f8a9b0-c1d2-4345-a678-901234ef0123

	/// Chiffre d'affaires HT (order_amount_eur).
	measure 'CA Total HT' = SUM(fact_commandes[ca_ht])
		formatString: #,##0.00 €
		lineageTag: dda226fa-8e6c-4c56-acbd-56fa1c84d136

	/// CA HT reconstruit — order_amount_eur natif si présent, sinon order_amount_local / taux mensuel moyen.
	/// Variante parallèle à [CA Total HT], sur le même modèle que [Marge Brute] vs [Marge Brute (prov.)].
	/// Voir docs/notes-techniques/reconstruction-ca-marketplace.md.
	measure 'CA Total HT (reconstruit)' = SUM(fact_commandes[ca_ht_reconstruit])
		formatString: #,##0.00 €
		lineageTag: f8091234-5678-9abc-def0-123456789abc

	/// Bloc3 (grain commande) — CA HT hors commandes annulées.
	/// Applique la règle Marc "CA=0 sur annulation" au grain commande.
	/// Ne capture PAS les annulations partielles (state <> CANCELLED, ~8 900 cmd,
	/// borne CA cf. limite-etf-annulation.md) — limite connue documentée.
	measure 'CA HT Net Annulation' =
			CALCULATE([CA Total HT], fact_commandes[state] <> "CANCELLED")
		formatString: #,##0.00 €
		lineageTag: f8091234-5678-9abc-def0-123456789abd

	/// Bloc3 (grain commande) — CA HT reconstruit hors commandes annulées.
	/// Variante marketplace (Bloc 1) de [CA HT Net Annulation].
	measure 'CA HT Net Annulation (reconstruit)' =
			CALCULATE([CA Total HT (reconstruit)], fact_commandes[state] <> "CANCELLED")
		formatString: #,##0.00 €
		lineageTag: f8091234-5678-9abc-def0-123456789abe

	/// Bloc3 (grain commande) — transparence : CA porté par les commandes en annulation
	/// partielle (state <> CANCELLED mais ≥1 article CANCELLED). Non ajusté faute de prix ligne.
	/// Identification via rel_lignes_commandes (pas de colonne calculée fact_commandes).
	measure 'CA Commandes Annulation Partielle' =
			CALCULATE(
				[CA Total HT],
				FILTER(
					fact_commandes,
					fact_commandes[state] <> "CANCELLED"
						&& COUNTROWS(
							FILTER(
								RELATEDTABLE(fact_lignes),
								fact_lignes[internal_state] = "CANCELLED"
							)
						) > 0
						&& COUNTROWS(
							FILTER(
								RELATEDTABLE(fact_lignes),
								fact_lignes[internal_state] <> "CANCELLED"
							)
						) > 0
				)
			)
		formatString: #,##0.00 €
		lineageTag: f8091234-5678-9abc-def0-123456789abf

	/// Coût d'achat total des livres (product_cost_eur).
	measure 'Coût Achat Total' = SUM(fact_commandes[cout_achat])
		formatString: #,##0.00 €
		lineageTag: 494ae678-7bb6-4cd5-a3c8-0e49d6296417

	/// Coût transport estimé par le backend (total_shipping_cost_to_delivery_country_eur).
	measure 'Coût Transport Estimé' = SUM(fact_commandes[cout_transport_estime])
		formatString: #,##0.00 €
		lineageTag: d0af07eb-f680-4e05-bc4b-b69de2131850

	/// Coût transport réel, issu des colis backend (package.shipping_cost_eur).
	measure 'Coût Transport Réel' = SUM(fact_transport[cout_transport])
		formatString: #,##0.00 €
		lineageTag: c596d85e-75bd-4785-88ba-ca8931c8a1b0

	/// Coût transport facturé par Colissimo/Chronopost (contrôle croisé).
	/// Fix F-06 : total facturé attribué au transporteur et à la date de la FACTURE elle-même
	/// (chemin direct). Comme rel_factures_transporteur / rel_factures_date sont inactives, on
	/// les active explicitement via USERELATIONSHIP et on coupe le chemin indirect (id_package)
	/// avec CROSSFILTER pour éviter toute ambiguïté.
	measure 'Coût Transport Facturé' =
			CALCULATE(
				SUM(fact_factures_transport[cout_transport]),
				USERELATIONSHIP(fact_factures_transport[transporteur], dim_transporteur[transporteur]),
				USERELATIONSHIP(fact_factures_transport[date_facture], dim_date[date]),
				CROSSFILTER(fact_factures_transport[id_package], fact_transport[id_package], None)
			)
		formatString: #,##0.00 €
		lineageTag: 0c73b641-d4e0-421c-af69-cdc593a9582e

	/// Fix F-05 : écart entre le coût transport RETENU (facturé si dispo, sinon estimé) et
	/// l'estimation backend commande. Remplace l'ancien [Écart Coût Transport] qui comparait
	/// deux estimations backend (coût colis vs coût commande), sans valeur de pilotage.
	measure 'Écart Coût Outbound vs Estimé Backend' =
			[Coût Transport Outbound (Retenu)] - [Coût Transport Estimé]
		formatString: #,##0.00 €
		lineageTag: f0b7ddaf-bbb7-42c0-9723-b40b9f621956

	/// Fix F-05 : écart coût outbound en % de l'estimé backend.
	measure 'Taux Écart Coût' = DIVIDE([Écart Coût Outbound vs Estimé Backend], [Coût Transport Estimé], 0)
		formatString: 0.0%
		lineageTag: 831022a0-57dc-4efe-b01b-6eee24553f25

	/// Coût transport réel moyen par colis.
	measure 'Coût Moyen Colis' = DIVIDE([Coût Transport Réel], [Nb Colis], 0)
		formatString: #,##0.00 €
		lineageTag: 82e52ba9-cea9-4b63-bbe3-1eac0361816e

	/// MARGE BRUTE — FORMULE PROVISOIRE. CA HT - coût d'achat - coût transport réel.
	/// Écart constaté le 12/07/2026 entre ce calcul simple et gross_profit_eur existant.
	/// À VALIDER avec Marc / finance avant de considérer comme définitive.
	measure 'Marge Brute (prov.)' = [CA Total HT] - [Coût Achat Total] - [Coût Transport Réel]
		formatString: #,##0.00 €
		lineageTag: 540144b1-b58e-46b7-8ca6-a31cc2c1da61

	/// Taux de marge brute (provisoire) = Marge Brute (prov.) / CA HT.
	measure 'Taux Marge Brute (prov.)' = DIVIDE([Marge Brute (prov.)], [CA Total HT], 0)
		formatString: 0.0%
		lineageTag: 55093196-dbb1-4824-bdbb-3de0469d326b

	/// Marge brute calculée par le backend (gross_profit_eur) — RÉFÉRENCE de contrôle.
	measure 'Marge Brute Backend (réf.)' = SUM(fact_commandes[gross_profit_eur])
		formatString: #,##0.00 €
		lineageTag: d5933b33-f893-4bba-862c-8a410050dbf1

	/// Écart entre la marge provisoire et la marge backend (aide à la validation finance).
	measure 'Écart Marge vs Backend' = [Marge Brute (prov.)] - [Marge Brute Backend (réf.)]
		formatString: #,##0.00 €
		lineageTag: 96da7a44-3aa5-400a-ae45-f6122da0451e

	/// Fix F-04 : frais de port encaissés par le client (marketplace notamment).
	/// Périmètre d'inclusion ("if relevant") non tranché — inclus par défaut dans [Marge Brute].
	measure 'Frais Port Encaissés' = SUM(fact_commandes[frais_port_encaisse])
		formatString: #,##0.00 €
		lineageTag: 5e6f7a8b-9c0d-4e1f-2a3b-4c5d6e7f8a9b

	/// Fix F-04 : coût de transport amont (inbound_transportation_cost_eur).
	measure 'Coût Transport Amont' = SUM(fact_commandes[cout_transport_amont])
		formatString: #,##0.00 €
		lineageTag: 6f7a8b9c-0d1e-4f2a-3b4c-5d6e7f8a9b0c

	/// Fix F-02/F-04 : coût transport outbound RETENU (facturé si rapproché, sinon estimé backend).
	measure 'Coût Transport Outbound (Retenu)' = SUM(fact_transport[cout_transport_retenu])
		formatString: #,##0.00 €
		lineageTag: 7a8b9c0d-1e2f-4a3b-4c5d-6e7f8a9b0c1d

	/// Fix F-04 : douanes et taxes (duties_taxes_eur) — poste "duties and taxes" de la formule Marc.
	measure 'Douanes Taxes' = SUM(fact_transport[duties_taxes_eur])
		formatString: #,##0.00 €
		lineageTag: 8b9c0d1e-2f3a-4b4c-5d6e-7f8a9b0c1d2e

	/// Fix F-04 : commissions marketplace (marketplace_fees_eur).
	measure 'Commissions Marketplace' = SUM(fact_commandes[commissions_marketplace])
		formatString: #,##0.00 €
		lineageTag: 9c0d1e2f-3a4b-4c5d-6e7f-8a9b0c1d2e3f

	/// Fix F-04 : fournitures d'expédition (shipping_supply_cost_eur).
	measure 'Fournitures Expédition' = SUM(fact_transport[shipping_supply_cost_eur])
		formatString: #,##0.00 €
		lineageTag: 0d1e2f3a-4b5c-4d6e-7f8a-9b0c1d2e3f4a

	/// Bloc5 (dette technique) — retours et remboursements (returns_and_refunds_cost_eur,
	/// agrégé par commande). Provisoire : Marc doit revoir le périmètre de son côté.
	/// Risque double comptage à valider avec Marc : sur CANCELLED, product_cost (cout_achat)
	/// est conservé ET returns_and_refunds est aussi soustrait — coexistence réelle dans les
	/// données (pas d'identité rr≈pc ; ratio médian rr/pc ≈ 2,4 %). Voir dette-technique-bloc5.md.
	measure 'Retours Remboursements' = SUM(fact_commandes[retours_remboursements])
		formatString: #,##0.00 €
		lineageTag: e8f9a0b1-c2d3-4456-e789-0123def01234

	/// Bloc5 (dette technique) — coûts génériques (generic_costs_eur, agrégé par commande).
	/// Provisoire : Marc doit revoir total_generic_costs_eur / la définition de generic costs
	/// de son côté avant de figer ce poste dans la marge.
	measure 'Coûts Génériques' = SUM(fact_commandes[couts_generiques])
		formatString: #,##0.00 €
		lineageTag: f9a0b1c2-d3e4-4567-f890-1234ef012345

	/// MARGE BRUTE — formule confirmée par Marc Bordier (Slack, 13/07/2026 16h09).
	/// Revenu = CA hors commandes annulées (règle Marc "CA=0 sur annulation", grain commande).
	/// Coûts conservés sur toutes commandes y compris annulées (décision Marc : coût produit
	/// + transport si après expédition). Frais de port encaissés exclus sur commandes CANCELLED
	/// (1 283 € sur l'entrepôt actuel, audit 15/07/2026). Annulations partielles non ajustées
	/// (~8 900 cmd, limite connue — voir docs/notes-techniques/limite-etf-annulation.md).
	/// Grain article [Marge Brute (grain article, prov.)] conservé comme contrôle et chemin de
	/// bascule si customer_price_per_item_eur devient disponible par ligne.
	/// Revenue (incl. shipping revenue if relevant) - COGS - Inbound transportation costs
	/// - Outbound transportation costs - Duties and Taxes - Marketplace commission fees
	/// - Shipping supplies - Returns/refunds - Generic costs.
	/// Retours/remboursements + coûts génériques inclus (Bloc 5, dette technique provisoire —
	/// Marc doit revoir total_generic_costs_eur ; valider risque double comptage returns/refunds
	/// vs product_cost conservé sur annulation). Grain commande (agrégés par order_id depuis
	/// customer_order_item).
	measure 'Marge Brute' =
			[CA HT Net Annulation]
				+ CALCULATE([Frais Port Encaissés], fact_commandes[state] <> "CANCELLED")
				- [Coût Achat Total]
				- [Coût Transport Amont]
				- [Coût Transport Outbound (Retenu)]
				- [Douanes Taxes]
				- [Commissions Marketplace]
				- [Fournitures Expédition]
				- [Retours Remboursements]
				- [Coûts Génériques]
		formatString: #,##0.00 €
		lineageTag: 1e2f3a4b-5c6d-4e7f-8a9b-0c1d2e3f4a5b

	/// Fix F-04 / C-01 : taux = Marge Brute / revenu net annulation
	/// ([CA HT Net Annulation] + frais port hors CANCELLED) — même périmètre que [Marge Brute].
	measure 'Taux Marge Brute' =
			DIVIDE(
				[Marge Brute],
				[CA HT Net Annulation]
					+ CALCULATE([Frais Port Encaissés], fact_commandes[state] <> "CANCELLED"),
				0
			)
		formatString: 0.0%
		lineageTag: 2f3a4b5c-6d7e-4f8a-9b0c-1d2e3f4a5b6c

	/// Fix F-04 : écart entre la marge conforme Marc et la marge backend (contrôle v2).
	measure 'Écart Marge vs Backend (v2)' = [Marge Brute] - [Marge Brute Backend (réf.)]
		formatString: #,##0.00 €
		lineageTag: 3a4b5c6d-7e8f-4a9b-0c1d-2e3f4a5b6c7d

	/// Nombre de commandes ayant au moins un colis avec facture transporteur rapprochée (source_cout = facture_rapprochee).
	measure 'Nb Commandes Matchées' = CALCULATE(DISTINCTCOUNT(fact_transport[order_id]), fact_transport[source_cout] = "facture_rapprochee")
		formatString: #,##0
		lineageTag: baae1892-caaa-4c58-be8e-a24bbf35a559

	/// Taux de matching facture = commandes avec coût réel (facture) / total commandes.
	measure 'Taux Matching' = DIVIDE([Nb Commandes Matchées], [Nb Commandes], 0)
		formatString: 0.0%
		lineageTag: c9fe02d1-af86-4e43-b409-66721938de41

	/// Commandes sans aucun colis rapproché à une facture transporteur.
	measure 'Nb Commandes Non Matchées' = [Nb Commandes] - [Nb Commandes Matchées]
		formatString: #,##0
		lineageTag: e49b07fe-49a0-4f51-8316-32d54fe32163

	/// Coût facturé (Colissimo/Chronopost) rapproché du colis via la relation rel_factures_colis
	/// (fact_factures_transport[id_package] -> fact_transport[id_package]), clé RÉSOLUE PAR DATE
	/// dans la partition. Remplace l'ancien TREATAS sur numero_suivi, qui rattachait la facture
	/// aux 2 colis d'un numéro de suivi recyclé (382 cas) => surcomptage.
	/// Fix F-06 : coût facturé attribué au COLIS via rel_factures_colis (clé id_package résolue
	/// par date). Relation active épinglée explicitement par USERELATIONSHIP plutôt que de
	/// compter sur une relation active implicite. Distinct de [Coût Transport Facturé] qui, lui,
	/// suit le chemin direct facture -> transporteur/date.
	measure 'Coût Facturé Rapproché' =
			CALCULATE(
				SUM(fact_factures_transport[cout_transport]),
				USERELATIONSHIP(fact_factures_transport[id_package], fact_transport[id_package])
			)
		formatString: #,##0.00 €
		lineageTag: c96ba0bc-9091-4ace-8974-29e4ffe02b25

	/// Écart entre le coût réel backend et le coût facturé transporteur (contrôle).
	/// Fix F-06 : le terme facturé passe par le chemin id_package (via [Coût Facturé Rapproché]),
	/// aligné au grain colis avec [Coût Transport Réel].
	measure 'Écart Réel vs Facturé' = [Coût Transport Réel] - [Coût Facturé Rapproché]
		formatString: #,##0.00 €
		lineageTag: e8bd1f63-4bcc-46c4-940e-133635ca4aac

	/// Nombre de colis rapprochés à une facture Colissimo/Chronopost (aligné sur source_cout = facture_rapprochee).
	measure 'Nb Colis Avec Facture' = [Nb Colis (coût réel)]
		formatString: #,##0
		lineageTag: cf7eab3c-beff-47d9-a425-381d83e6a41a

	/// Taux de rapprochement facture = colis avec facture / total colis.
	measure 'Taux Matching Factures' = DIVIDE([Nb Colis Avec Facture], [Nb Colis], 0)
		formatString: 0.0%
		lineageTag: 83eb47a3-ddff-4106-a391-6f55c64f38f7

	/// Panier moyen HT par commande.
	measure 'Panier Moyen' = DIVIDE([CA Total HT], [Nb Commandes], 0)
		formatString: #,##0.00 €
		lineageTag: 1b392be4-7f29-413b-8881-e29c3d1c99ed

	/// Poids total expédié (kg).
	measure 'Poids Total (kg)' = SUM(fact_transport[poids_kg])
		formatString: #,##0.000
		lineageTag: 594bb787-db4c-4e44-b6d2-184b63c29975

	/// Marge brute provisoire cumulée sur l'année (YTD).
	measure 'Marge YTD (prov.)' = TOTALYTD([Marge Brute (prov.)], dim_date[date])
		formatString: #,##0.00 €
		lineageTag: 28cf665e-0ecc-4980-b6cd-40f0dd3b6f10

	/// CA HT du mois précédent (time intelligence).
	measure 'CA Mois Précédent' = CALCULATE([CA Total HT], DATEADD(dim_date[date], -1, MONTH))
		formatString: #,##0.00 €
		lineageTag: 0868e48b-09c3-46ed-a947-9930a529aedf

	/// Évolution du CA vs mois précédent (%).
	measure 'Évolution CA' = DIVIDE([CA Total HT] - [CA Mois Précédent], [CA Mois Précédent], 0)
		formatString: 0.0%
		lineageTag: 97de0e8d-69dd-49d3-8d74-7a8a41d51a9e

	/// Chronopost : lignes au-delà de la 1re par numero_facture (grain multi-colis, pas un doublon qualité).
	measure 'Lignes Colis par Facture (hors 1re)' =
			VAR T =
				ADDCOLUMNS(
					FILTER(
						VALUES(fact_factures_transport[numero_facture]),
						NOT ISBLANK(fact_factures_transport[numero_facture])
							&& fact_factures_transport[numero_facture] <> ""
					),
					"Cnt", CALCULATE(COUNTROWS(fact_factures_transport))
				)
			RETURN
				SUMX(FILTER(T, [Cnt] > 1), [Cnt] - 1)
		formatString: #,##0
		lineageTag: f1a2b3c4-d5e6-4789-a012-3456789abcde

	/// Vrais doublons qualité : même numero_facture ET même numero_suivi sur plusieurs lignes.
	measure 'Vrais Doublons (Facture + Suivi)' =
			VAR T =
				ADDCOLUMNS(
					SUMMARIZE(
						fact_factures_transport,
						fact_factures_transport[numero_facture],
						fact_factures_transport[numero_suivi]
					),
					"Cnt", CALCULATE(COUNTROWS(fact_factures_transport))
				)
			RETURN
				SUMX(FILTER(T, [Cnt] > 1), [Cnt] - 1)
		formatString: #,##0
		lineageTag: e6f78901-2345-4567-f567-89abcdef0123

	/// Lignes de facture dont numero_suivi apparaît plus d'une fois (surplus hors 1re occurrence).
	measure 'Doublons Numero Suivi Factures' =
			VAR T =
				ADDCOLUMNS(
					VALUES(fact_factures_transport[numero_suivi]),
					"Cnt", CALCULATE(COUNTROWS(fact_factures_transport))
				)
			RETURN
				SUMX(FILTER(T, [Cnt] > 1), [Cnt] - 1)
		formatString: #,##0
		lineageTag: a2b3c4d5-e6f7-4890-b123-456789abcdef

	/// Commandes hors CANCELLED sans aucun colis dans fact_transport (162 attendu sur entrepôt actuel).
	measure 'Commandes Sans Colis' =
			COUNTROWS(
				FILTER(
					fact_commandes,
					fact_commandes[state] <> "CANCELLED"
						&& COUNTROWS(RELATEDTABLE(fact_transport)) = 0
				)
			)
		formatString: #,##0
		lineageTag: b3c4d5e6-f789-4012-c234-56789abcdef0

	/// Colis dont order_id ne correspond à aucune commande (intégrité référentielle).
	measure 'Colis Sans Commande' =
			COUNTROWS(
				FILTER(
					fact_transport,
					ISBLANK(RELATED(fact_commandes[id_commande]))
				)
			)
		formatString: #,##0
		lineageTag: c4d5e6f7-8901-4234-d345-6789abcdef01

	/// Lignes de facture chargées avec cout_transport nul ou absent.
	measure 'Lignes Facture Coût Transport Zero ou Null' =
			COUNTROWS(
				FILTER(
					fact_factures_transport,
					ISBLANK(fact_factures_transport[cout_transport])
						|| fact_factures_transport[cout_transport] = 0
				)
			)
		formatString: #,##0
		lineageTag: d5e6f789-0123-4345-e456-789abcdef012

	/// =====================================================================
	/// Bloc 8 — KPI Finance + time intelligence YoY (SAMEPERIODLASTYEAR).
	/// Prérequis : dim_date continue depuis 2020. DIVIDE sans 3e arg → BLANK
	/// si dénominateur PY nul / absent.
	/// =====================================================================

	/// Finance KPI — Ordered Units (alias [Nb Articles], grain article / date_commande).
	measure 'Unités commandées' = [Nb Articles]
		formatString: #,##0
		lineageTag: 62d36844-d7c6-4108-bb36-42ec9c44c92c

	/// Finance KPI — Revenue = CA produit net annulation + frais de port (hors CANCELLED).
	/// Aligné sur le dénominateur de [Taux Marge Brute].
	measure Revenu =
			[CA HT Net Annulation]
				+ CALCULATE([Frais Port Encaissés], fact_commandes[state] <> "CANCELLED")
		formatString: #,##0.00 €
		lineageTag: 4449f741-c626-42a0-95c8-c0226f4e7f11

	/// --- KPI cards : Unités commandées (Ordered Units) ---
	measure 'Unités commandées PY' = CALCULATE([Unités commandées], SAMEPERIODLASTYEAR(dim_date[date]))
		formatString: #,##0
		lineageTag: dc99c916-a9a6-42a2-acfa-e7dd0b88b42a

	measure 'Unités commandées YoY Δ' = [Unités commandées] - [Unités commandées PY]
		formatString: #,##0
		lineageTag: 63169707-a053-4e3b-a825-b5ac033932d0

	measure 'Unités commandées YoY %' = DIVIDE([Unités commandées] - [Unités commandées PY], [Unités commandées PY])
		formatString: 0.0%
		lineageTag: b2b7b172-1298-4d91-ba61-d1142ba285a3

	/// --- KPI cards : Revenu (Revenue) ---
	measure 'Revenu PY' = CALCULATE([Revenu], SAMEPERIODLASTYEAR(dim_date[date]))
		formatString: #,##0.00 €
		lineageTag: b6b7aeab-d880-4342-8a60-5663277104df

	measure 'Revenu YoY Δ' = [Revenu] - [Revenu PY]
		formatString: #,##0.00 €
		lineageTag: 61fb369e-68bb-4d68-9514-2c4448bb0e73

	measure 'Revenu YoY %' = DIVIDE([Revenu] - [Revenu PY], [Revenu PY])
		formatString: 0.0%
		lineageTag: 2891b13d-7576-4fae-acc3-746871b32126

	/// --- KPI cards : Marge Brute (Gross Profit) ---
	measure 'Marge Brute PY' = CALCULATE([Marge Brute], SAMEPERIODLASTYEAR(dim_date[date]))
		formatString: #,##0.00 €
		lineageTag: 7e2bb4b1-508f-4fec-b635-ced01e74cc21

	measure 'Marge Brute YoY Δ' = [Marge Brute] - [Marge Brute PY]
		formatString: #,##0.00 €
		lineageTag: 2bccadc5-5cad-4801-83a0-b72471a37ece

	measure 'Marge Brute YoY %' = DIVIDE([Marge Brute] - [Marge Brute PY], [Marge Brute PY])
		formatString: 0.0%
		lineageTag: 0c2bedcf-84e7-4297-8deb-7507f03ee820

	/// --- KPI cards : Taux Marge Brute (Gross Margin %) — YoY en bps, pas en % ---
	measure 'Taux Marge Brute PY' = CALCULATE([Taux Marge Brute], SAMEPERIODLASTYEAR(dim_date[date]))
		formatString: 0.0%
		lineageTag: 671212f3-1065-4868-adce-a3a95fe37ea4

	measure 'Taux Marge Brute YoY bps' = ([Taux Marge Brute] - [Taux Marge Brute PY]) * 10000
		formatString: #,##0
		lineageTag: 90ed7a8b-a675-4b89-9642-5b5798c3ed86

	/// --- Tableaux détaillés P&L : même logique PY / YoY Δ / YoY % ---

	measure 'Nb Commandes PY' = CALCULATE([Nb Commandes], SAMEPERIODLASTYEAR(dim_date[date]))
		formatString: #,##0
		lineageTag: c06ad058-babd-4af3-9382-8e8f7d87de2a

	measure 'Nb Commandes YoY Δ' = [Nb Commandes] - [Nb Commandes PY]
		formatString: #,##0
		lineageTag: 4f1666f1-50a1-45a9-a53e-a1707d2e6b4e

	measure 'Nb Commandes YoY %' = DIVIDE([Nb Commandes] - [Nb Commandes PY], [Nb Commandes PY])
		formatString: 0.0%
		lineageTag: a9eaf4fa-cdb1-42bc-b812-4e4175876d98

	measure 'CA HT Net Annulation PY' = CALCULATE([CA HT Net Annulation], SAMEPERIODLASTYEAR(dim_date[date]))
		formatString: #,##0.00 €
		lineageTag: b375dae1-e80e-4327-8270-83f36c50a2ad

	measure 'CA HT Net Annulation YoY Δ' = [CA HT Net Annulation] - [CA HT Net Annulation PY]
		formatString: #,##0.00 €
		lineageTag: 41d555c8-ff35-47ba-89b9-8b94949401bc

	measure 'CA HT Net Annulation YoY %' = DIVIDE([CA HT Net Annulation] - [CA HT Net Annulation PY], [CA HT Net Annulation PY])
		formatString: 0.0%
		lineageTag: 4d5f0088-0032-49e6-a591-1f1adb7f0e7a

	measure 'Frais Port Encaissés PY' = CALCULATE([Frais Port Encaissés], SAMEPERIODLASTYEAR(dim_date[date]))
		formatString: #,##0.00 €
		lineageTag: 3c8c29e4-4493-41b2-b9c5-62213d939366

	measure 'Frais Port Encaissés YoY Δ' = [Frais Port Encaissés] - [Frais Port Encaissés PY]
		formatString: #,##0.00 €
		lineageTag: 875190ab-308d-46c5-bcfd-60658b92d4cb

	measure 'Frais Port Encaissés YoY %' = DIVIDE([Frais Port Encaissés] - [Frais Port Encaissés PY], [Frais Port Encaissés PY])
		formatString: 0.0%
		lineageTag: 875b244b-fff6-4c17-94a1-9d8b16639d33

	measure 'Coût Achat Total PY' = CALCULATE([Coût Achat Total], SAMEPERIODLASTYEAR(dim_date[date]))
		formatString: #,##0.00 €
		lineageTag: 62fde7f2-0dab-4203-859c-3f41e6b8e8c9

	measure 'Coût Achat Total YoY Δ' = [Coût Achat Total] - [Coût Achat Total PY]
		formatString: #,##0.00 €
		lineageTag: 6a77f5e5-4ac2-45d1-98c9-58927eb3a98b

	measure 'Coût Achat Total YoY %' = DIVIDE([Coût Achat Total] - [Coût Achat Total PY], [Coût Achat Total PY])
		formatString: 0.0%
		lineageTag: c1b2cbdc-fcbd-4283-85bb-f8633178bfc9

	measure 'Coût Transport Amont PY' = CALCULATE([Coût Transport Amont], SAMEPERIODLASTYEAR(dim_date[date]))
		formatString: #,##0.00 €
		lineageTag: 51d9ecde-f889-44e4-940e-026bab6fc47c

	measure 'Coût Transport Amont YoY Δ' = [Coût Transport Amont] - [Coût Transport Amont PY]
		formatString: #,##0.00 €
		lineageTag: 9666c508-db96-4550-a7d8-87c287095111

	measure 'Coût Transport Amont YoY %' = DIVIDE([Coût Transport Amont] - [Coût Transport Amont PY], [Coût Transport Amont PY])
		formatString: 0.0%
		lineageTag: 0fca9897-d9bd-4ff6-8c5c-8cd4727b1cef

	measure 'Coût Transport Outbound (Retenu) PY' = CALCULATE([Coût Transport Outbound (Retenu)], SAMEPERIODLASTYEAR(dim_date[date]))
		formatString: #,##0.00 €
		lineageTag: c4ce4585-9c86-47ea-a88d-d7d89b50e5fd

	measure 'Coût Transport Outbound (Retenu) YoY Δ' = [Coût Transport Outbound (Retenu)] - [Coût Transport Outbound (Retenu) PY]
		formatString: #,##0.00 €
		lineageTag: 5f0b3520-1bcd-4770-8dba-25664442aa5c

	measure 'Coût Transport Outbound (Retenu) YoY %' = DIVIDE([Coût Transport Outbound (Retenu)] - [Coût Transport Outbound (Retenu) PY], [Coût Transport Outbound (Retenu) PY])
		formatString: 0.0%
		lineageTag: 8bcbd401-4e41-421b-9af7-3ccc383fb0ba

	measure 'Douanes Taxes PY' = CALCULATE([Douanes Taxes], SAMEPERIODLASTYEAR(dim_date[date]))
		formatString: #,##0.00 €
		lineageTag: f000cb0d-655f-4ba1-a763-e8ab5d69a443

	measure 'Douanes Taxes YoY Δ' = [Douanes Taxes] - [Douanes Taxes PY]
		formatString: #,##0.00 €
		lineageTag: 16fbcfd2-dde6-4481-b4cf-b65158d16e68

	measure 'Douanes Taxes YoY %' = DIVIDE([Douanes Taxes] - [Douanes Taxes PY], [Douanes Taxes PY])
		formatString: 0.0%
		lineageTag: 6147462f-8305-4568-8404-63a1abee626f

	measure 'Commissions Marketplace PY' = CALCULATE([Commissions Marketplace], SAMEPERIODLASTYEAR(dim_date[date]))
		formatString: #,##0.00 €
		lineageTag: 09d9cbe9-ce73-470d-97d0-6cba4c2de600

	measure 'Commissions Marketplace YoY Δ' = [Commissions Marketplace] - [Commissions Marketplace PY]
		formatString: #,##0.00 €
		lineageTag: 4028c4bb-382f-458c-94cf-316ab739d77a

	measure 'Commissions Marketplace YoY %' = DIVIDE([Commissions Marketplace] - [Commissions Marketplace PY], [Commissions Marketplace PY])
		formatString: 0.0%
		lineageTag: 2f8200f8-dd17-43d9-b73f-c499062f2d77

	measure 'Fournitures Expédition PY' = CALCULATE([Fournitures Expédition], SAMEPERIODLASTYEAR(dim_date[date]))
		formatString: #,##0.00 €
		lineageTag: 99df3b5d-eab6-4918-b040-24adefd6b1b0

	measure 'Fournitures Expédition YoY Δ' = [Fournitures Expédition] - [Fournitures Expédition PY]
		formatString: #,##0.00 €
		lineageTag: ffb87dd7-ee17-425c-bae7-67260d253f0f

	measure 'Fournitures Expédition YoY %' = DIVIDE([Fournitures Expédition] - [Fournitures Expédition PY], [Fournitures Expédition PY])
		formatString: 0.0%
		lineageTag: 86d98470-ce8d-45aa-979d-fc7701f189d4

	measure 'Retours Remboursements PY' = CALCULATE([Retours Remboursements], SAMEPERIODLASTYEAR(dim_date[date]))
		formatString: #,##0.00 €
		lineageTag: e430624b-7acd-4eec-a764-b0dd52df83d0

	measure 'Retours Remboursements YoY Δ' = [Retours Remboursements] - [Retours Remboursements PY]
		formatString: #,##0.00 €
		lineageTag: 8ccd792d-079b-4dbd-956d-b44fac89a5c3

	measure 'Retours Remboursements YoY %' = DIVIDE([Retours Remboursements] - [Retours Remboursements PY], [Retours Remboursements PY])
		formatString: 0.0%
		lineageTag: 0fe4f423-5830-4f64-880f-93e2e40ab98b

	measure 'Coûts Génériques PY' = CALCULATE([Coûts Génériques], SAMEPERIODLASTYEAR(dim_date[date]))
		formatString: #,##0.00 €
		lineageTag: b962c013-7f99-440e-9eee-43f9219e752f

	measure 'Coûts Génériques YoY Δ' = [Coûts Génériques] - [Coûts Génériques PY]
		formatString: #,##0.00 €
		lineageTag: 1747e9bb-8b28-4b36-8697-5932f1cc2918

	measure 'Coûts Génériques YoY %' = DIVIDE([Coûts Génériques] - [Coûts Génériques PY], [Coûts Génériques PY])
		formatString: 0.0%
		lineageTag: 625464b5-de13-4b23-8028-5c54a97ab079

	column Dummy
		lineageTag: 8b077e7c-c0c2-475a-9b63-bed5f82bf07a
		summarizeBy: none
		sourceColumn: [Dummy]

	partition _Mesures = calculated
		mode: import
		source = ROW("Dummy", BLANK())

