/// Dimension — calendrier (2020-01-01 -> 2026-12-31), libellés en français.
/// Étendue à 2020 pour couvrir l'historique backend (origin_created dès 2020-01)
/// et permettre le YoY sur toute la plage. Table générée en Power Query
/// (indépendante des sources). Reliée à fact_commandes[date_commande] et
/// fact_factures_transport[date_facture].
table dim_date
	lineageTag: 1ae962f8-740f-448c-901d-b26c93c27570
	dataCategory: Time

	column date
		dataType: dateTime
		isKey
		formatString: yyyy-MM-dd
		lineageTag: 3bdec9d9-5d0e-4b61-a426-61abab59c3a6
		dataCategory: Time
		summarizeBy: none
		sourceColumn: date

		changedProperty = IsHidden

		annotation UnderlyingDateTimeDataType = Date

	column annee
		dataType: int64
		formatString: 0
		lineageTag: 36f972cc-209d-4bba-8196-46a3e30b97cc
		summarizeBy: sum
		sourceColumn: annee

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column trimestre
		dataType: int64
		formatString: 0
		lineageTag: 92a43465-a60e-4214-abec-6a90bae4198a
		summarizeBy: sum
		sourceColumn: trimestre

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column mois
		dataType: int64
		formatString: 0
		lineageTag: 8c1e0563-4270-46b1-a859-64e95d0d0569
		summarizeBy: sum
		sourceColumn: mois

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	/// Nom du mois (français), trié par le numéro de mois.
	column nom_mois
		dataType: string
		lineageTag: 92cf5609-1abe-4863-b0c7-29eb72b13909
		summarizeBy: none
		sourceColumn: nom_mois
		sortByColumn: mois

		changedProperty = IsHidden

	/// Clé année-mois (AAAAMM) pour tri/filtre chronologique.
	column annee_mois
		dataType: int64
		formatString: 0
		lineageTag: ca110d35-f1c5-45a1-92d9-ec604bf863d1
		summarizeBy: sum
		sourceColumn: annee_mois

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column semaine
		dataType: int64
		formatString: 0
		lineageTag: 5357d0b5-e469-40a6-9c57-d1a8d30a07c0
		summarizeBy: sum
		sourceColumn: semaine

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	/// Jour de la semaine (français), trié du lundi au dimanche.
	column jour_semaine
		dataType: string
		lineageTag: b624f43d-b8ce-4ab6-97b3-b0ad628f6c98
		summarizeBy: none
		sourceColumn: jour_semaine
		sortByColumn: num_jour_semaine

		changedProperty = IsHidden

	column num_jour_semaine
		dataType: int64
		formatString: 0
		lineageTag: aab51cc0-e48f-4306-9b4a-50921e76ac13
		summarizeBy: sum
		sourceColumn: num_jour_semaine

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	/// Libellé semaine ISO (AAA-Sww) — axe graphe General View.
	column semaine_annee_libelle
		dataType: string
		lineageTag: d1e2f3a4-b5c6-7890-dabc-ef1234567890
		summarizeBy: none
		sourceColumn: semaine_annee_libelle

		changedProperty = IsHidden

	/// Libellé mois + année — axe graphe General View.
	column nom_mois_annee
		dataType: string
		lineageTag: e2f3a4b5-c6d7-8901-bcde-f23456789012
		summarizeBy: none
		sourceColumn: nom_mois_annee
		sortByColumn: annee_mois

		changedProperty = IsHidden

	/// Libellé mois court anglais (Jul 25) — axe chart General View V1.
	column mois_annee_court_en
		dataType: string
		lineageTag: f3a4b5c6-d7e8-9012-cdef-345678901234
		summarizeBy: none
		sourceColumn: mois_annee_court_en
		sortByColumn: annee_mois

		changedProperty = IsHidden

	partition dim_date = m
		mode: import
		source =
				let
					// Bornes du calendrier (historique backend dès 2020 — requis pour YoY)
					Debut = #date(2020, 1, 1),
					Fin = #date(2026, 12, 31),
					NbJours = Duration.Days(Fin - Debut) + 1,
					// Génération de la liste continue de dates
					ListeDates = List.Dates(Debut, NbJours, #duration(1, 0, 0, 0)),
					#"Table des dates" = Table.FromList(ListeDates, Splitter.SplitByNothing(), {"date"}),
					#"Date typee" = Table.TransformColumnTypes(#"Table des dates", {{"date", type date}}),
					// Attributs calendaires (libellés fr-FR)
					#"Annee ajoutee" = Table.AddColumn(#"Date typee", "annee", each Date.Year([date]), Int64.Type),
					#"Trimestre ajoute" = Table.AddColumn(#"Annee ajoutee", "trimestre", each Date.QuarterOfYear([date]), Int64.Type),
					#"Mois ajoute" = Table.AddColumn(#"Trimestre ajoute", "mois", each Date.Month([date]), Int64.Type),
					#"Nom mois ajoute" = Table.AddColumn(#"Mois ajoute", "nom_mois", each Date.ToText([date], [Format = "MMMM", Culture = "fr-FR"]), type text),
					#"Annee mois ajoutee" = Table.AddColumn(#"Nom mois ajoute", "annee_mois", each [annee] * 100 + [mois], Int64.Type),
					#"Semaine ajoutee" = Table.AddColumn(#"Annee mois ajoutee", "semaine", each Date.WeekOfYear([date], Day.Monday), Int64.Type),
					#"Jour semaine ajoute" = Table.AddColumn(#"Semaine ajoutee", "jour_semaine", each Date.ToText([date], [Format = "dddd", Culture = "fr-FR"]), type text),
					#"Num jour semaine ajoute" = Table.AddColumn(#"Jour semaine ajoute", "num_jour_semaine", each Date.DayOfWeek([date], Day.Monday) + 1, Int64.Type),
					#"Semaine annee libelle" = Table.AddColumn(
						#"Num jour semaine ajoute",
						"semaine_annee_libelle",
						each Text.From([annee]) & "-S" & Text.PadStart(Text.From([semaine]), 2, "0"),
						type text
					),
					#"Nom mois annee" = Table.AddColumn(
						#"Semaine annee libelle",
						"nom_mois_annee",
						each [nom_mois] & " " & Text.From([annee]),
						type text
					),
					#"Mois annee court EN" = Table.AddColumn(
						#"Nom mois annee",
						"mois_annee_court_en",
						each Date.ToText([date], [Format = "MMM yy", Culture = "en-US"]),
						type text
					)
				in
					#"Mois annee court EN"

