/// Dimension — type de commande (axe d'analyse du dashboard).
/// Dérivée des valeurs distinctes de customer_order.source (canal de vente).
/// Colonne canal : regroupement Finance (Website B2C / Website B2B / Marketplaces /
/// Librairie Arthaud / Autre). Mapping validé provisoirement — PRO_WEBSITE = Website B2B
/// à confirmer avec Marc.
table dim_type_commande
	lineageTag: 429de86e-9e69-49ed-bcff-fcd4d672de50

	column type_commande
		dataType: string
		lineageTag: f494be33-15be-43b4-a792-bd6d6ed4d5c0
		summarizeBy: none
		sourceColumn: type_commande

		changedProperty = IsHidden

	column canal
		dataType: string
		lineageTag: c4d80b3e-bab1-4dbd-b1ef-e50399ec9c0d
		summarizeBy: none
		sourceColumn: canal

		changedProperty = IsHidden

	column libelle
		dataType: string
		lineageTag: 6026a2bd-9ca5-474c-8514-bf4b6cf47a48
		summarizeBy: none
		sourceColumn: libelle

		changedProperty = IsHidden

	partition dim_type_commande = m
		mode: import
		source =
				let
					// Canaux distincts (via staging partagé)
					#"Colonne source" = Table.SelectColumns(stg_customer_order, {"source"}),
					// Normalisation de la clé type_commande (repli INCONNU)
					#"Type commande derive" = Table.AddColumn(#"Colonne source", "type_commande", each if [source] = null or Text.Trim([source]) = "" then "INCONNU" else Text.Trim([source]), type text),
					#"Valeurs distinctes" = Table.Distinct(Table.SelectColumns(#"Type commande derive", {"type_commande"})),
					// Mapping Canal validé provisoirement — PRO_WEBSITE = Website B2B à confirmer avec Marc
					#"Canal ajoute" = Table.AddColumn(#"Valeurs distinctes", "canal", each
						let s = Text.Upper([type_commande]) in
						if s = "WEBSITE" then "Website B2C"
						else if s = "PRO_WEBSITE" then "Website B2B"
						else if Text.StartsWith(s, "AMAZON") or s = "CULTURA" or s = "RAKUTEN" or s = "FNAC" then "Marketplaces"
						else if s = "ARTHAUD" then "Librairie Arthaud"
						else "Autre", type text),
					// Libellé lisible (underscores -> espaces, casse normalisée)
					#"Libelle ajoute" = Table.AddColumn(#"Canal ajoute", "libelle", each Text.Proper(Text.Replace([type_commande], "_", " ")), type text)
				in
					#"Libelle ajoute"

