/// Dimension — type de commande (axe d'analyse du dashboard).
/// Dérivée des valeurs distinctes de customer_order.source (canal de vente).
/// Catégorisation par règle (Marketplace / B2C direct / B2B / Autre) — à valider
/// avec Lireka pour la nomenclature métier définitive.
table dim_type_commande
	lineageTag: 429de86e-9e69-49ed-bcff-fcd4d672de50

	column type_commande
		dataType: string
		lineageTag: f494be33-15be-43b4-a792-bd6d6ed4d5c0
		summarizeBy: none
		sourceColumn: type_commande

	column categorie
		dataType: string
		lineageTag: c4d80b3e-bab1-4dbd-b1ef-e50399ec9c0d
		summarizeBy: none
		sourceColumn: categorie

	column libelle
		dataType: string
		lineageTag: 6026a2bd-9ca5-474c-8514-bf4b6cf47a48
		summarizeBy: none
		sourceColumn: libelle

	partition dim_type_commande = m
		mode: import
		source =
				let
					// Lecture de la source pour récupérer les canaux distincts
					Source = Csv.Document(File.Contents(DossierDonnees & "\Données_Backend\customer_order.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
					#"En-tetes promus" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
					#"Colonne source" = Table.SelectColumns(#"En-tetes promus", {"source"}),
					// Normalisation de la clé type_commande (repli INCONNU)
					#"Type commande derive" = Table.AddColumn(#"Colonne source", "type_commande", each if [source] = null or Text.Trim([source]) = "" then "INCONNU" else Text.Trim([source]), type text),
					#"Valeurs distinctes" = Table.Distinct(Table.SelectColumns(#"Type commande derive", {"type_commande"})),
					// Catégorisation métier par règle
					#"Categorie ajoutee" = Table.AddColumn(#"Valeurs distinctes", "categorie", each
						let s = Text.Upper([type_commande]) in
						if s = "WEBSITE" then "B2C direct"
						else if Text.StartsWith(s, "AMAZON") then "Marketplace"
						else if Text.Contains(s, "B2B") then "B2B"
						else if Text.Contains(s, "FNAC") or Text.Contains(s, "CDISCOUNT") or Text.Contains(s, "EBAY") or Text.Contains(s, "RAKUTEN") then "Marketplace"
						else if s = "INCONNU" then "Non identifié"
						else "Autre", type text),
					// Libellé lisible (underscores -> espaces, casse normalisée)
					#"Libelle ajoute" = Table.AddColumn(#"Categorie ajoutee", "libelle", each Text.Proper(Text.Replace([type_commande], "_", " ")), type text)
				in
					#"Libelle ajoute"

