/// Dimension — catalogue ISBN (grain : un ISBN).
/// Clé = isbn ; ISBN distincts de customer_order_item_group (PostgreSQL, même grain que fact_lignes[isbn]).
/// title / author : vides tant qu'aucune vue catalogue n'est disponible en base (stg_catalogue_isbn = table vide).
table dim_isbn
	lineageTag: d1m2i3s4-b5n6-7890-abcd-ef1234567890

	column isbn
		dataType: string
		lineageTag: d1m2i3s4-b5n6-7890-abcd-ef1234567891
		summarizeBy: none
		sourceColumn: isbn

	column title
		dataType: string
		lineageTag: d1m2i3s4-b5n6-7890-abcd-ef1234567892
		summarizeBy: none
		sourceColumn: title

	column author
		dataType: string
		lineageTag: d1m2i3s4-b5n6-7890-abcd-ef1234567893
		summarizeBy: none
		sourceColumn: author

	partition dim_isbn = m
		mode: import
		source =
				let
					// ISBN distincts calculés par PostgreSQL (majuscules + trim : clé insensible à la casse comme VertiPaq,
					// même normalisation que fact_lignes[isbn]).
					#"Groupes source" = fnRequeteSql("SELECT DISTINCT upper(trim(isbn)) AS isbn FROM " & PgSchema & ".customer_order_item_group"),
					#"Isbns types" = Table.TransformColumnTypes(
						Table.SelectColumns(#"Groupes source", {"isbn"}),
						{{"isbn", type text}},
						"en-US"
					),
					#"Isbns distincts" = Table.Distinct(#"Isbns types"),
					#"Isbns valides" = Table.SelectRows(
						#"Isbns distincts",
						each [isbn] <> null and Text.Trim([isbn]) <> ""
					),
					#"Jointure catalogue" = Table.NestedJoin(
						#"Isbns valides",
						{"isbn"},
						stg_catalogue_isbn,
						{"isbn"},
						"cat",
						JoinKind.LeftOuter
					),
					#"Catalogue developpe" = Table.ExpandTableColumn(
						#"Jointure catalogue",
						"cat",
						{"title", "author"},
						{"title", "author"}
					)
				in
					#"Catalogue developpe"

