/// Dimension — pays de livraison (axe d'analyse du dashboard).
/// Clés = codes ISO 3166-1 alpha-2 réellement présents dans customer_order
/// (destination_country), enrichis d'un libellé FR, d'un libellé EN (V1 rapport)
/// et d'une zone. Les codes non mappés retombent sur le libellé ISO EN puis le code.
table dim_pays
	lineageTag: 558c4b12-b228-4ccc-b432-5f25c225e488

	column code_pays
		dataType: string
		lineageTag: f49c62ae-6b71-4157-be2f-108245ca2495
		summarizeBy: none
		sourceColumn: code_pays

		changedProperty = IsHidden

	column nom_pays
		dataType: string
		lineageTag: 13a14901-53a1-4294-a326-ca8b1de78b39
		summarizeBy: none
		sourceColumn: nom_pays

		changedProperty = IsHidden

	column zone_geo
		dataType: string
		lineageTag: fc874ea6-56b4-43e0-9677-bd3ec5912945
		summarizeBy: none
		sourceColumn: zone_geo

		changedProperty = IsHidden

	column continent
		dataType: string
		lineageTag: a1819b4f-b8ff-4ab1-9ba1-9748501ae966
		summarizeBy: none
		sourceColumn: continent

		changedProperty = IsHidden

	/// Libellé anglais (V1 rapport tout anglais) — USA, Germany, South Africa…
	column nom_pays_en
		dataType: string
		lineageTag: 13a14901-53a1-4294-a326-ca8b1de78b40
		summarizeBy: none
		sourceColumn: nom_pays_en

		changedProperty = IsHidden

	partition dim_pays = m
		mode: import
		source =
				let
					// Distinct dynamique depuis stg_customer_order (SelectColumns tôt, pas de Buffer).
					#"Codes bruts" = Table.SelectColumns(stg_customer_order, {"destination_country"}),
					#"Codes normalises" = Table.AddColumn(
						#"Codes bruts",
						"code_pays",
						each if [destination_country] = null or Text.Trim([destination_country]) = "" then "??"
							else Text.Upper(Text.Trim([destination_country])),
						type text
					),
					#"Codes distincts" = Table.Distinct(Table.SelectColumns(#"Codes normalises", {"code_pays"})),
					// Table de correspondance code -> nom FR / zone / continent
					Correspondance = #table(
						type table [code_pays = text, nom_pays = text, zone_geo = text, continent = text],
						{
							{"FR", "France", "Europe de l'Ouest", "Europe"},
							{"BE", "Belgique", "Europe de l'Ouest", "Europe"},
							{"LU", "Luxembourg", "Europe de l'Ouest", "Europe"},
							{"CH", "Suisse", "Europe de l'Ouest", "Europe"},
							{"DE", "Allemagne", "Europe de l'Ouest", "Europe"},
							{"NL", "Pays-Bas", "Europe de l'Ouest", "Europe"},
							{"AT", "Autriche", "Europe de l'Ouest", "Europe"},
							{"ES", "Espagne", "Europe du Sud", "Europe"},
							{"IT", "Italie", "Europe du Sud", "Europe"},
							{"PT", "Portugal", "Europe du Sud", "Europe"},
							{"GB", "Royaume-Uni", "Europe du Nord", "Europe"},
							{"IE", "Irlande", "Europe du Nord", "Europe"},
							{"DK", "Danemark", "Europe du Nord", "Europe"},
							{"SE", "Suède", "Europe du Nord", "Europe"},
							{"NO", "Norvège", "Europe du Nord", "Europe"},
							{"FI", "Finlande", "Europe du Nord", "Europe"},
							{"PL", "Pologne", "Europe de l'Est", "Europe"},
							{"CZ", "Tchéquie", "Europe de l'Est", "Europe"},
							{"US", "États-Unis", "Amérique du Nord", "Amérique"},
							{"CA", "Canada", "Amérique du Nord", "Amérique"},
							{"MX", "Mexique", "Amérique du Nord", "Amérique"},
							{"BR", "Brésil", "Amérique du Sud", "Amérique"},
							{"AU", "Australie", "Océanie", "Océanie"},
							{"NZ", "Nouvelle-Zélande", "Océanie", "Océanie"},
							{"JP", "Japon", "Asie", "Asie"},
							{"CN", "Chine", "Asie", "Asie"},
							{"SG", "Singapour", "Asie", "Asie"},
							{"HK", "Hong Kong", "Asie", "Asie"},
							{"AE", "Émirats arabes unis", "Moyen-Orient", "Asie"},
							{"MA", "Maroc", "Afrique du Nord", "Afrique"},
							{"DZ", "Algérie", "Afrique du Nord", "Afrique"},
							{"TN", "Tunisie", "Afrique du Nord", "Afrique"},
							{"ZA", "Afrique du Sud", "Afrique subsaharienne", "Afrique"},
							{"RE", "Réunion", "DOM-TOM", "France d'outre-mer"},
							{"GP", "Guadeloupe", "DOM-TOM", "France d'outre-mer"},
							{"MQ", "Martinique", "DOM-TOM", "France d'outre-mer"},
							{"GF", "Guyane", "DOM-TOM", "France d'outre-mer"},
							{"YT", "Mayotte", "DOM-TOM", "France d'outre-mer"},
							{"NC", "Nouvelle-Calédonie", "DOM-TOM", "France d'outre-mer"},
							{"PF", "Polynésie française", "DOM-TOM", "France d'outre-mer"},
							// Résidu volontairement marqué : commandes sans destination_country conservées
							// (non-CANCELLED) pour ne pas faire disparaître leur CA/volume — décision 14/07/2026.
							{"??", "Pays non attribué", "Non attribué", "Non attribué"}
						}),
					// Libellés anglais ISO (V1 rapport) — USA / Germany / South Africa…
					IsoEn = #table(
						type table [code_pays = text, nom_pays_en = text],
						{
							{"??", "Unassigned country"},
							{"AD", "Andorra"},
							{"AE", "United Arab Emirates"},
							{"AF", "Afghanistan"},
							{"AG", "Antigua and Barbuda"},
							{"AI", "Anguilla"},
							{"AL", "Albania"},
							{"AM", "Armenia"},
							{"AN", "Netherlands Antilles"},
							{"AO", "Angola"},
							{"AQ", "Antarctica"},
							{"AR", "Argentina"},
							{"AS", "American Samoa"},
							{"AT", "Austria"},
							{"AU", "Australia"},
							{"AW", "Aruba"},
							{"AX", "Aland Islands"},
							{"AZ", "Azerbaijan"},
							{"BA", "Bosnia and Herzegovina"},
							{"BB", "Barbados"},
							{"BD", "Bangladesh"},
							{"BE", "Belgium"},
							{"BF", "Burkina Faso"},
							{"BG", "Bulgaria"},
							{"BH", "Bahrain"},
							{"BI", "Burundi"},
							{"BJ", "Benin"},
							{"BL", "Saint Barthelemy"},
							{"BM", "Bermuda"},
							{"BN", "Brunei"},
							{"BO", "Bolivia"},
							{"BQ", "Caribbean Netherlands"},
							{"BR", "Brazil"},
							{"BS", "Bahamas"},
							{"BT", "Bhutan"},
							{"BV", "Bouvet Island"},
							{"BW", "Botswana"},
							{"BY", "Belarus"},
							{"BZ", "Belize"},
							{"CA", "Canada"},
							{"CC", "Cocos Islands"},
							{"CD", "DR Congo"},
							{"CF", "Central African Republic"},
							{"CG", "Congo"},
							{"CH", "Switzerland"},
							{"CI", "Ivory Coast"},
							{"CK", "Cook Islands"},
							{"CL", "Chile"},
							{"CM", "Cameroon"},
							{"CN", "China"},
							{"CO", "Colombia"},
							{"CR", "Costa Rica"},
							{"CU", "Cuba"},
							{"CV", "Cape Verde"},
							{"CW", "Curacao"},
							{"CX", "Christmas Island"},
							{"CY", "Cyprus"},
							{"CZ", "Czechia"},
							{"DE", "Germany"},
							{"DJ", "Djibouti"},
							{"DK", "Denmark"},
							{"DM", "Dominica"},
							{"DO", "Dominican Republic"},
							{"DZ", "Algeria"},
							{"EC", "Ecuador"},
							{"EE", "Estonia"},
							{"EG", "Egypt"},
							{"EH", "Western Sahara"},
							{"ER", "Eritrea"},
							{"ES", "Spain"},
							{"ET", "Ethiopia"},
							{"FI", "Finland"},
							{"FJ", "Fiji"},
							{"FK", "Falkland Islands"},
							{"FM", "Micronesia"},
							{"FO", "Faroe Islands"},
							{"FR", "France"},
							{"GA", "Gabon"},
							{"GB", "United Kingdom"},
							{"GD", "Grenada"},
							{"GE", "Georgia"},
							{"GF", "French Guiana"},
							{"GG", "Guernsey"},
							{"GH", "Ghana"},
							{"GI", "Gibraltar"},
							{"GL", "Greenland"},
							{"GM", "Gambia"},
							{"GN", "Guinea"},
							{"GP", "Guadeloupe"},
							{"GQ", "Equatorial Guinea"},
							{"GR", "Greece"},
							{"GS", "South Georgia"},
							{"GT", "Guatemala"},
							{"GU", "Guam"},
							{"GW", "Guinea-Bissau"},
							{"GY", "Guyana"},
							{"HK", "Hong Kong"},
							{"HM", "Heard Island"},
							{"HN", "Honduras"},
							{"HR", "Croatia"},
							{"HT", "Haiti"},
							{"HU", "Hungary"},
							{"ID", "Indonesia"},
							{"IE", "Ireland"},
							{"IL", "Israel"},
							{"IM", "Isle of Man"},
							{"IN", "India"},
							{"IO", "British Indian Ocean Territory"},
							{"IQ", "Iraq"},
							{"IR", "Iran"},
							{"IS", "Iceland"},
							{"IT", "Italy"},
							{"JE", "Jersey"},
							{"JM", "Jamaica"},
							{"JO", "Jordan"},
							{"JP", "Japan"},
							{"KE", "Kenya"},
							{"KG", "Kyrgyzstan"},
							{"KH", "Cambodia"},
							{"KI", "Kiribati"},
							{"KM", "Comoros"},
							{"KN", "Saint Kitts and Nevis"},
							{"KP", "North Korea"},
							{"KR", "South Korea"},
							{"KW", "Kuwait"},
							{"KY", "Cayman Islands"},
							{"KZ", "Kazakhstan"},
							{"LA", "Laos"},
							{"LB", "Lebanon"},
							{"LC", "Saint Lucia"},
							{"LI", "Liechtenstein"},
							{"LK", "Sri Lanka"},
							{"LR", "Liberia"},
							{"LS", "Lesotho"},
							{"LT", "Lithuania"},
							{"LU", "Luxembourg"},
							{"LV", "Latvia"},
							{"LY", "Libya"},
							{"MA", "Morocco"},
							{"MC", "Monaco"},
							{"MD", "Moldova"},
							{"ME", "Montenegro"},
							{"MF", "Saint Martin"},
							{"MG", "Madagascar"},
							{"MH", "Marshall Islands"},
							{"MK", "North Macedonia"},
							{"ML", "Mali"},
							{"MM", "Myanmar"},
							{"MN", "Mongolia"},
							{"MO", "Macao"},
							{"MP", "Northern Mariana Islands"},
							{"MQ", "Martinique"},
							{"MR", "Mauritania"},
							{"MS", "Montserrat"},
							{"MT", "Malta"},
							{"MU", "Mauritius"},
							{"MV", "Maldives"},
							{"MW", "Malawi"},
							{"MX", "Mexico"},
							{"MY", "Malaysia"},
							{"MZ", "Mozambique"},
							{"NA", "Namibia"},
							{"NC", "New Caledonia"},
							{"NE", "Niger"},
							{"NF", "Norfolk Island"},
							{"NG", "Nigeria"},
							{"NI", "Nicaragua"},
							{"NL", "Netherlands"},
							{"NO", "Norway"},
							{"NP", "Nepal"},
							{"NR", "Nauru"},
							{"NU", "Niue"},
							{"NZ", "New Zealand"},
							{"OM", "Oman"},
							{"PA", "Panama"},
							{"PE", "Peru"},
							{"PF", "French Polynesia"},
							{"PG", "Papua New Guinea"},
							{"PH", "Philippines"},
							{"PK", "Pakistan"},
							{"PL", "Poland"},
							{"PM", "Saint Pierre and Miquelon"},
							{"PN", "Pitcairn Islands"},
							{"PR", "Puerto Rico"},
							{"PS", "Palestine"},
							{"PT", "Portugal"},
							{"PW", "Palau"},
							{"PY", "Paraguay"},
							{"QA", "Qatar"},
							{"RE", "Reunion"},
							{"RO", "Romania"},
							{"RS", "Serbia"},
							{"RU", "Russia"},
							{"RW", "Rwanda"},
							{"SA", "Saudi Arabia"},
							{"SB", "Solomon Islands"},
							{"SC", "Seychelles"},
							{"SD", "Sudan"},
							{"SE", "Sweden"},
							{"SG", "Singapore"},
							{"SH", "Saint Helena"},
							{"SI", "Slovenia"},
							{"SJ", "Svalbard and Jan Mayen"},
							{"SK", "Slovakia"},
							{"SL", "Sierra Leone"},
							{"SM", "San Marino"},
							{"SN", "Senegal"},
							{"SO", "Somalia"},
							{"SR", "Suriname"},
							{"SS", "South Sudan"},
							{"ST", "Sao Tome and Principe"},
							{"SV", "El Salvador"},
							{"SX", "Sint Maarten"},
							{"SY", "Syria"},
							{"SZ", "Eswatini"},
							{"TC", "Turks and Caicos Islands"},
							{"TD", "Chad"},
							{"TF", "French Southern Territories"},
							{"TG", "Togo"},
							{"TH", "Thailand"},
							{"TJ", "Tajikistan"},
							{"TK", "Tokelau"},
							{"TL", "Timor-Leste"},
							{"TM", "Turkmenistan"},
							{"TN", "Tunisia"},
							{"TO", "Tonga"},
							{"TR", "Turkey"},
							{"TT", "Trinidad and Tobago"},
							{"TV", "Tuvalu"},
							{"TW", "Taiwan"},
							{"TZ", "Tanzania"},
							{"UA", "Ukraine"},
							{"UG", "Uganda"},
							{"UM", "US Minor Outlying Islands"},
							{"US", "USA"},
							{"UY", "Uruguay"},
							{"UZ", "Uzbekistan"},
							{"VA", "Vatican City"},
							{"VC", "Saint Vincent and the Grenadines"},
							{"VE", "Venezuela"},
							{"VG", "British Virgin Islands"},
							{"VI", "US Virgin Islands"},
							{"VN", "Vietnam"},
							{"VU", "Vanuatu"},
							{"WF", "Wallis and Futuna"},
							{"WS", "Samoa"},
							{"XK", "Kosovo"},
							{"YE", "Yemen"},
							{"YT", "Mayotte"},
							{"ZA", "South Africa"},
							{"ZM", "Zambia"},
							{"ZW", "Zimbabwe"}
						}),
					#"Codes enrichis" = Table.NestedJoin(#"Codes distincts", {"code_pays"}, Correspondance, {"code_pays"}, "corr", JoinKind.LeftOuter),
					#"Correspondance etendue" = Table.ExpandTableColumn(#"Codes enrichis", "corr", {"nom_pays", "zone_geo", "continent"}, {"nom_pays", "zone_geo", "continent"}),
					#"Codes EN" = Table.NestedJoin(#"Correspondance etendue", {"code_pays"}, IsoEn, {"code_pays"}, "en", JoinKind.LeftOuter),
					#"EN etendu" = Table.ExpandTableColumn(#"Codes EN", "en", {"nom_pays_en"}, {"nom_pays_en"}),
					#"Nom par defaut" = Table.AddColumn(#"EN etendu", "nom_pays_final", each [nom_pays] ?? [code_pays], type text),
					#"Nom EN par defaut" = Table.AddColumn(#"Nom par defaut", "nom_pays_en_final", each [nom_pays_en] ?? [code_pays], type text),
					#"Zone par defaut" = Table.AddColumn(#"Nom EN par defaut", "zone_geo_final", each [zone_geo] ?? "Autre / à classer", type text),
					#"Continent par defaut" = Table.AddColumn(#"Zone par defaut", "continent_final", each [continent] ?? "Autre", type text),
					#"Colonnes finales" = Table.SelectColumns(#"Continent par defaut", {"code_pays", "nom_pays_final", "nom_pays_en_final", "zone_geo_final", "continent_final"}),
					#"Colonnes renommees" = Table.RenameColumns(
						#"Colonnes finales",
						{
							{"nom_pays_final", "nom_pays"},
							{"nom_pays_en_final", "nom_pays_en"},
							{"zone_geo_final", "zone_geo"},
							{"continent_final", "continent"}
						}
					),
					// Ligne bucket tableau B2C — aucune facture liée (code synthétique).
					#"Avec Rest of the world" = Table.Combine(
						{
							#"Colonnes renommees",
							#table(
								type table [code_pays = text, nom_pays = text, nom_pays_en = text, zone_geo = text, continent = text],
								{{"__ROW__", "Reste du monde", "Rest of the world", "Rest of the world", "Rest of the world"}}
							)
						}
					)
				in
					#"Avec Rest of the world"

