/// Faits — lignes de factures transporteurs (PostgreSQL analytics_views.v_carrier_invoice_lines).
/// Le backend rattache chaque ligne au colis (package_id) et à la commande (order_id) :
/// aucun rapprochement par numéro de suivi ni par date côté Power BI.
/// Alimenté par stg_factures_transport_resolu.
table fact_factures_transport
	lineageTag: 3e48232a-1883-4a3e-bf86-44d0d480d1fa

	/// Date de la facture (clé vers dim_date).
	column date_facture
		dataType: dateTime
		formatString: yyyy-MM-dd
		lineageTag: ae273671-c725-47cd-abaa-2bb0e89acd27
		summarizeBy: none
		sourceColumn: date_facture

		changedProperty = IsHidden

		annotation UnderlyingDateTimeDataType = Date

	/// Transporteur canonique (carrier_name normalisé par fnCanonTransporteur).
	column transporteur
		dataType: string
		lineageTag: 4550186f-ae1e-4003-8ca0-6fe6f9300d5e
		summarizeBy: none
		sourceColumn: transporteur

		changedProperty = IsHidden

	column service
		dataType: string
		lineageTag: 10db3ac1-f9f1-4847-aa55-18b0d80f8724
		summarizeBy: none
		sourceColumn: service

		changedProperty = IsHidden

	/// Pays de destination (invoice_country_code).
	column pays_destination
		dataType: string
		lineageTag: 899d1dc8-28bb-492c-be09-bb1be241d2c9
		summarizeBy: none
		sourceColumn: pays_destination

		changedProperty = IsHidden

	column poids
		dataType: double
		formatString: #,##0.000
		lineageTag: 1605cb0c-7a09-4959-9929-bbadb56a058a
		summarizeBy: sum
		sourceColumn: poids

		changedProperty = IsHidden

	/// Coût transport facturé HT en EUR (amount_excl_vat_eur).
	column cout_transport
		dataType: double
		formatString: #,##0.00 €
		lineageTag: 125e8180-2944-4f06-a00f-186548827da1
		summarizeBy: sum
		sourceColumn: cout_transport

		changedProperty = IsHidden

	column devise
		dataType: string
		lineageTag: cbbfc9cf-c110-481d-9dc7-c1eea172df42
		summarizeBy: none
		sourceColumn: devise

		changedProperty = IsHidden

	/// Commande rattachée (order_id fourni par le backend).
	column order_id
		dataType: int64
		isHidden
		lineageTag: 7b1f0c2d-3e4a-4b5c-8d6e-9f0a1b2c3d4e
		summarizeBy: none
		sourceColumn: order_id

	/// Colis rattaché (clé vers fact_transport, package_id fourni par le backend).
	column id_package
		dataType: int64
		isHidden
		lineageTag: 8c2a1d3e-4f5b-4c6d-9e7f-0a1b2c3d4e5f
		summarizeBy: none
		sourceColumn: id_package

	column nb_candidats_resolution
		dataType: double
		lineageTag: b6aa5601-0dc0-4bc9-bf43-70ab5ea68934
		summarizeBy: sum
		sourceColumn: nb_candidats_resolution

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition fact_factures_transport = m
		mode: import
		source = Table.AddColumn(stg_factures_transport_resolu, "devise", each "EUR", type text)

