/// Faits — commandes clients (grain : une ligne par commande).
/// Source locale : Données_Backend/customer_order.csv (File.Contents via stg_customer_order).
/// Clé : id_commande (customer_order.id). Porte le CA, les coûts backend et
/// la marge existante (gross_profit_eur) conservée comme référence de contrôle.
table fact_commandes
	lineageTag: 11fa5581-3c36-4afa-ae59-a9cc19e15f69

	column id_commande
		dataType: int64
		isHidden
		lineageTag: 463339a0-5b78-4230-a496-61ef20b8aca3
		summarizeBy: none
		sourceColumn: id_commande

	column origin_order_id
		dataType: string
		lineageTag: b5efc10c-9a0b-454a-962a-6e58acc360a1
		summarizeBy: none
		sourceColumn: origin_order_id

		changedProperty = IsHidden

	column state
		dataType: string
		lineageTag: d552aead-fcf3-4c76-852d-52f81f7ea027
		summarizeBy: none
		sourceColumn: state

		changedProperty = IsHidden

	column source
		dataType: string
		lineageTag: 196d52ee-a2ce-4dc7-98b2-827d28f8e4a8
		summarizeBy: none
		sourceColumn: source

		changedProperty = IsHidden

	/// Axe d'analyse "type de commande" — dérivé de customer_order.source
	/// (canal de vente : WEBSITE, AMAZON_FR, ...). Interprétation à valider avec Lireka.
	column type_commande
		dataType: string
		lineageTag: f217ab35-b208-4bf8-877a-7eac9a4cb025
		summarizeBy: none
		sourceColumn: type_commande

		changedProperty = IsHidden

	/// Code pays de livraison ISO 3166-1 alpha-2 (destination_country). "??" si absent.
	column code_pays
		dataType: string
		lineageTag: f7d25057-6a3d-4a16-a18c-9d7405a8190b
		summarizeBy: none
		sourceColumn: code_pays

		changedProperty = IsHidden

	column currency
		dataType: string
		lineageTag: 49714872-95db-44f0-867a-8ecf6044a06c
		summarizeBy: none
		sourceColumn: currency

		changedProperty = IsHidden

	/// Chiffre d'affaires HT en EUR (order_amount_eur).
	column ca_ht
		dataType: double
		formatString: #,##0.00 €
		lineageTag: da448a96-2d78-471b-a902-701f6b5826fc
		summarizeBy: sum
		sourceColumn: ca_ht

		changedProperty = IsHidden

	/// CA HT reconstruit en EUR (order_amount_eur natif ou order_amount_local / taux mensuel).
	/// Voir commentaire Power Query dans la partition et docs/notes-techniques/reconstruction-ca-marketplace.md.
	column ca_ht_reconstruit
		dataType: double
		formatString: #,##0.00 €
		lineageTag: e7f80912-a3b4-5678-9abc-def012345678
		summarizeBy: sum
		sourceColumn: ca_ht_reconstruit

		changedProperty = IsHidden

	/// Fix F-04 : frais de port encaissés auprès du client en EUR (shipping_fee_eur).
	/// Renommé shipping_fee_eur -> frais_port_encaisse pour exposer le poste
	/// "shipping revenue" de la formule Marc à la mesure [Frais Port Encaissés].
	column frais_port_encaisse
		dataType: double
		formatString: #,##0.00 €
		lineageTag: 52d273ed-6508-4932-bff1-838a5a742071
		summarizeBy: sum
		sourceColumn: frais_port_encaisse

		changedProperty = IsHidden

	/// Fix F-04 : coût de transport amont (inbound_transportation_cost_eur) — poste
	/// "inbound transportation costs" de la formule Marc.
	column cout_transport_amont
		dataType: double
		formatString: #,##0.00 €
		lineageTag: 1a2b3c4d-5e6f-4a7b-8c9d-0e1f2a3b4c5d
		summarizeBy: sum
		sourceColumn: cout_transport_amont

		changedProperty = IsHidden

	/// Fix F-04 : commissions marketplace (marketplace_fees_eur) — poste
	/// "marketplace commission fees (fixed and variable)" de la formule Marc.
	column commissions_marketplace
		dataType: double
		formatString: #,##0.00 €
		lineageTag: 2b3c4d5e-6f7a-4b8c-9d0e-1f2a3b4c5d6e
		summarizeBy: sum
		sourceColumn: commissions_marketplace

		changedProperty = IsHidden

	/// Bloc5 (dette technique) — retours et remboursements agrégés par commande
	/// (SUM returns_and_refunds_cost_eur depuis customer_order_item). Périmètre provisoire.
	column retours_remboursements
		dataType: double
		formatString: #,##0.00 €
		lineageTag: c6d7e8f9-a0b1-4234-c567-8901bcdef012
		summarizeBy: sum
		sourceColumn: retours_remboursements

		changedProperty = IsHidden

	/// Bloc5 (dette technique) — coûts génériques agrégés par commande
	/// (SUM generic_costs_eur depuis customer_order_item). Périmètre provisoire.
	column couts_generiques
		dataType: double
		formatString: #,##0.00 €
		lineageTag: d7e8f9a0-b1c2-4345-d678-9012cdef0123
		summarizeBy: sum
		sourceColumn: couts_generiques

		changedProperty = IsHidden

	/// Coût d'achat des livres en EUR (product_cost_eur).
	column cout_achat
		dataType: double
		formatString: #,##0.00 €
		lineageTag: 0303a735-7e7b-4bff-8814-6fd3cf44e57c
		summarizeBy: sum
		sourceColumn: cout_achat

		changedProperty = IsHidden

	/// Coût transport estimé par le backend (total_shipping_cost_to_delivery_country_eur).
	column cout_transport_estime
		dataType: double
		formatString: #,##0.00 €
		lineageTag: 79df602e-014e-4609-a7b7-a507fbd957bb
		summarizeBy: sum
		sourceColumn: cout_transport_estime

		changedProperty = IsHidden

	/// Marge brute calculée par le backend Lireka — RÉFÉRENCE de contrôle uniquement.
	column gross_profit_eur
		dataType: double
		formatString: #,##0.00 €
		lineageTag: f936cdd0-712e-4107-a083-08085058721b
		summarizeBy: sum
		sourceColumn: gross_profit_eur

		changedProperty = IsHidden

	column gross_margin
		dataType: double
		formatString: 0.0%
		lineageTag: 284dce96-d29d-47cc-aa2e-4efe3a4de945
		summarizeBy: none
		sourceColumn: gross_margin

		changedProperty = IsHidden

	column contribution_profit_eur
		dataType: double
		formatString: #,##0.00 €
		lineageTag: 3958fe58-b33f-4fae-9e18-9493fc0c905e
		summarizeBy: sum
		sourceColumn: contribution_profit_eur

		changedProperty = IsHidden

	column contribution_margin
		dataType: double
		formatString: 0.0%
		lineageTag: 423d5a02-6639-4ac1-bea1-21532a5f4993
		summarizeBy: none
		sourceColumn: contribution_margin

		changedProperty = IsHidden

	/// Date de la commande (origin_created tronqué au jour). Clé vers dim_date.
	column date_commande
		dataType: dateTime
		formatString: yyyy-MM-dd
		lineageTag: 420154ac-c0fc-48be-ba16-c422162d47db
		summarizeBy: none
		sourceColumn: date_commande

		changedProperty = IsHidden

		annotation UnderlyingDateTimeDataType = Date

	/// Page 11 Loss analysis : marge brute au grain commande (formule [Marge Brute] a 10 postes).
	/// Outbound = cout_transport_retenu (facture rapprochee si dispo, sinon backend), pre-agrege depuis fact_transport.
	/// CANCELLED : CA et frais de port a 0 en ligne (les postes de cout restent inchanges).
	column marge_brute_commande
		dataType: double
		formatString: #,##0.00 €
		lineageTag: c011a001-4e11-4a11-8a11-000000000001
		summarizeBy: sum
		sourceColumn: marge_brute_commande

	/// Canal pour medianes / poste basculant (meme regle M qu'avant extraction DAX).
	column canal_bascule
		dataType: string
		isHidden
		lineageTag: c011a001-4e11-4a11-8a11-000000000010
		summarizeBy: none
		sourceColumn: canal_bascule

	/// CA HT net annulation (0 si CANCELLED) — entree des ratios mediane et du poste basculant.
	column ca_ht_net
		dataType: double
		isHidden
		formatString: #,##0.00 €
		lineageTag: c011a001-4e11-4a11-8a11-000000000011
		summarizeBy: sum
		sourceColumn: ca_ht_net

	/// Outbound retenu agrege par commande (depuis fact_transport) — grain poste basculant.
	column cout_transport_retenu_cmd
		dataType: double
		isHidden
		formatString: #,##0.00 €
		lineageTag: c011a001-4e11-4a11-8a11-000000000012
		summarizeBy: sum
		sourceColumn: cout_transport_retenu_cmd

	/// Douanes agregees par commande (depuis fact_transport).
	column duties_taxes_cmd
		dataType: double
		isHidden
		formatString: #,##0.00 €
		lineageTag: c011a001-4e11-4a11-8a11-000000000013
		summarizeBy: sum
		sourceColumn: duties_taxes_cmd

	/// Fournitures agregees par commande (depuis fact_transport).
	column fournitures_cmd
		dataType: double
		isHidden
		formatString: #,##0.00 €
		lineageTag: c011a001-4e11-4a11-8a11-000000000014
		summarizeBy: sum
		sourceColumn: fournitures_cmd

	/// Mediane canal du ratio cout_achat / ca_ht_net (Power Query).
	column med_r_achat
		dataType: double
		isHidden
		lineageTag: c011a001-4e11-4a11-8a11-000000000020
		summarizeBy: none
		sourceColumn: med_r_achat

	/// Mediane canal du ratio cout_transport_amont / ca_ht_net (Power Query).
	column med_r_amont
		dataType: double
		isHidden
		lineageTag: c011a001-4e11-4a11-8a11-000000000021
		summarizeBy: none
		sourceColumn: med_r_amont

	/// Mediane canal du ratio cout_transport_retenu_cmd / ca_ht_net (Power Query).
	column med_r_outbound
		dataType: double
		isHidden
		lineageTag: c011a001-4e11-4a11-8a11-000000000022
		summarizeBy: none
		sourceColumn: med_r_outbound

	/// Mediane canal du ratio duties_taxes_cmd / ca_ht_net (Power Query).
	column med_r_duties
		dataType: double
		isHidden
		lineageTag: c011a001-4e11-4a11-8a11-000000000023
		summarizeBy: none
		sourceColumn: med_r_duties

	/// Mediane canal du ratio commissions_marketplace / ca_ht_net (Power Query).
	column med_r_commissions
		dataType: double
		isHidden
		lineageTag: c011a001-4e11-4a11-8a11-000000000024
		summarizeBy: none
		sourceColumn: med_r_commissions

	/// Mediane canal du ratio fournitures_cmd / ca_ht_net (Power Query).
	column med_r_fournitures
		dataType: double
		isHidden
		lineageTag: c011a001-4e11-4a11-8a11-000000000025
		summarizeBy: none
		sourceColumn: med_r_fournitures

	/// Mediane canal du ratio retours_remboursements / ca_ht_net (Power Query).
	column med_r_retours
		dataType: double
		isHidden
		lineageTag: c011a001-4e11-4a11-8a11-000000000026
		summarizeBy: none
		sourceColumn: med_r_retours

	/// Mediane canal du ratio couts_generiques / ca_ht_net (Power Query).
	column med_r_generiques
		dataType: double
		isHidden
		lineageTag: c011a001-4e11-4a11-8a11-000000000027
		summarizeBy: none
		sourceColumn: med_r_generiques

	/// Page 11 Loss analysis : poste de cout qui, ramene a la mediane canal non deficitaire, suffit a basculer en marge positive.
	/// Vide si marge >= 0. Libelles EN (affiche client). Tie-break = premier de la liste (comparaison stricte, ordre M historique).
	column poste_basculant =
			IF(
				fact_commandes[marge_brute_commande] >= 0,
				BLANK(),
				VAR ca = fact_commandes[ca_ht_net]
				VAR m0 = fact_commandes[marge_brute_commande]
				VAR v_achat = IF(ISBLANK(fact_commandes[cout_achat]), 0, fact_commandes[cout_achat])
				VAR v_amont = IF(ISBLANK(fact_commandes[cout_transport_amont]), 0, fact_commandes[cout_transport_amont])
				VAR v_outbound = IF(ISBLANK(fact_commandes[cout_transport_retenu_cmd]), 0, fact_commandes[cout_transport_retenu_cmd])
				VAR v_duties = IF(ISBLANK(fact_commandes[duties_taxes_cmd]), 0, fact_commandes[duties_taxes_cmd])
				VAR v_commissions = IF(ISBLANK(fact_commandes[commissions_marketplace]), 0, fact_commandes[commissions_marketplace])
				VAR v_fournitures = IF(ISBLANK(fact_commandes[fournitures_cmd]), 0, fact_commandes[fournitures_cmd])
				VAR v_retours = IF(ISBLANK(fact_commandes[retours_remboursements]), 0, fact_commandes[retours_remboursements])
				VAR v_generiques = IF(ISBLANK(fact_commandes[couts_generiques]), 0, fact_commandes[couts_generiques])
				VAR med_achat = IF(ISBLANK(fact_commandes[med_r_achat]), 0, fact_commandes[med_r_achat])
				VAR med_amont = IF(ISBLANK(fact_commandes[med_r_amont]), 0, fact_commandes[med_r_amont])
				VAR med_outbound = IF(ISBLANK(fact_commandes[med_r_outbound]), 0, fact_commandes[med_r_outbound])
				VAR med_duties = IF(ISBLANK(fact_commandes[med_r_duties]), 0, fact_commandes[med_r_duties])
				VAR med_commissions = IF(ISBLANK(fact_commandes[med_r_commissions]), 0, fact_commandes[med_r_commissions])
				VAR med_fournitures = IF(ISBLANK(fact_commandes[med_r_fournitures]), 0, fact_commandes[med_r_fournitures])
				VAR med_retours = IF(ISBLANK(fact_commandes[med_r_retours]), 0, fact_commandes[med_r_retours])
				VAR med_generiques = IF(ISBLANK(fact_commandes[med_r_generiques]), 0, fact_commandes[med_r_generiques])
				VAR a1 = v_achat - med_achat * ca
				VAR n1 = m0 + a1
				VAR a2 = v_amont - med_amont * ca
				VAR n2 = m0 + a2
				VAR a3 = v_outbound - med_outbound * ca
				VAR n3 = m0 + a3
				VAR a4 = v_duties - med_duties * ca
				VAR n4 = m0 + a4
				VAR a5 = v_commissions - med_commissions * ca
				VAR n5 = m0 + a5
				VAR a6 = v_fournitures - med_fournitures * ca
				VAR n6 = m0 + a6
				VAR a7 = v_retours - med_retours * ca
				VAR n7 = m0 + a7
				VAR a8 = v_generiques - med_generiques * ca
				VAR n8 = m0 + a8
				VAR s0_a = -1.0E+100
				VAR s1_a = IF(n1 > 0 && a1 > s0_a, a1, s0_a)
				VAR s1_l = IF(n1 > 0 && a1 > s0_a, "Cost of goods", BLANK())
				VAR s2_a = IF(n2 > 0 && a2 > s1_a, a2, s1_a)
				VAR s2_l = IF(n2 > 0 && a2 > s1_a, "Inbound transport", s1_l)
				VAR s3_a = IF(n3 > 0 && a3 > s2_a, a3, s2_a)
				VAR s3_l = IF(n3 > 0 && a3 > s2_a, "Outbound transport", s2_l)
				VAR s4_a = IF(n4 > 0 && a4 > s3_a, a4, s3_a)
				VAR s4_l = IF(n4 > 0 && a4 > s3_a, "Duties and taxes", s3_l)
				VAR s5_a = IF(n5 > 0 && a5 > s4_a, a5, s4_a)
				VAR s5_l = IF(n5 > 0 && a5 > s4_a, "Marketplace commissions", s4_l)
				VAR s6_a = IF(n6 > 0 && a6 > s5_a, a6, s5_a)
				VAR s6_l = IF(n6 > 0 && a6 > s5_a, "Shipping supplies", s5_l)
				VAR s7_a = IF(n7 > 0 && a7 > s6_a, a7, s6_a)
				VAR s7_l = IF(n7 > 0 && a7 > s6_a, "Returns and refunds", s6_l)
				VAR s8_a = IF(n8 > 0 && a8 > s7_a, a8, s7_a)
				VAR s8_l = IF(n8 > 0 && a8 > s7_a, "Generic costs", s7_l)
				RETURN IF(ISBLANK(s8_l), "Structurally loss-making", s8_l)
			)
		dataType: string
		lineageTag: c011a001-4e11-4a11-8a11-000000000002
		summarizeBy: none

	/// Page 11 Loss analysis : tranche de panier (order_amount_eur / ca_ht), bornes 0/15/20/30/40/70/90/200.
	column tranche_panier
		dataType: string
		lineageTag: c011a001-4e11-4a11-8a11-000000000003
		summarizeBy: none
		sourceColumn: tranche_panier
		sortByColumn: tranche_panier_ordre

	/// Ordre d'affichage de tranche_panier (1..8). Colonne de tri uniquement.
	column tranche_panier_ordre
		dataType: int64
		formatString: 0
		lineageTag: c011a001-4e11-4a11-8a11-000000000004
		summarizeBy: none
		sourceColumn: tranche_panier_ordre

	partition fact_commandes = m
		mode: import
		source =
				let
					// Fix F-04 : typage des postes de marge manquants (inbound + commissions marketplace)
					// avant de les exposer au modèle. shipping_fee_eur / duties / supplies déjà typés en amont.
					#"Types postes marge" = Table.TransformColumnTypes(stg_customer_order, {
						{"inbound_transportation_cost_eur", type number},
						{"marketplace_fees_eur", type number}
					}, "en-US"),
					#"Date commande ajoutee" = Table.AddColumn(#"Types postes marge", "date_commande", each try Date.FromText(Text.Start([origin_created], 10), [Format = "yyyy-MM-dd"]) otherwise null, type date),
					#"Annee mois ajoutee" = Table.AddColumn(
						#"Date commande ajoutee",
						"annee_mois",
						each if [date_commande] = null then null else Date.Year([date_commande]) * 100 + Date.Month([date_commande]),
						Int64.Type
					),
					// CA reconstruit marketplace (taux moyen mensuel).
					#"Jointure taux mensuel" = Table.NestedJoin(
						#"Annee mois ajoutee",
						{"currency", "annee_mois"},
						stg_taux_moyen_mensuel,
						{"devise", "annee_mois"},
						"taux",
						JoinKind.LeftOuter
					),
					#"Taux mensuel etendu" = Table.ExpandTableColumn(#"Jointure taux mensuel", "taux", {"taux_moyen_mensuel"}, {"taux_moyen_mensuel"}),
					#"CA eur reconstruit" = Table.AddColumn(
						#"Taux mensuel etendu",
						"order_amount_eur_reconstruit",
						each
							let
								eurNatif = [order_amount_eur]
								// Neutralisation fallback FX (19/07) : order_amount_eur natif partout ;
								// branche local/taux non validée (sous-éval. x10 AMAZON) → null si absent.
							in
								if eurNatif <> null and eurNatif <> 0 then eurNatif
								else null,
						type nullable number
					),
					#"Code pays normalise" = Table.AddColumn(#"CA eur reconstruit", "code_pays", each if [destination_country] = null or Text.Trim([destination_country]) = "" then "??" else Text.Upper(Text.Trim([destination_country])), type text),
					#"Type commande derive" = Table.AddColumn(#"Code pays normalise", "type_commande", each if [source] = null or Text.Trim([source]) = "" then "INCONNU" else Text.Trim([source]), type text),
					#"Colonnes renommees" = Table.RenameColumns(#"Type commande derive", {
						{"id", "id_commande"},
						{"order_amount_eur", "ca_ht"},
						{"order_amount_eur_reconstruit", "ca_ht_reconstruit"},
						{"product_cost_eur", "cout_achat"},
						{"total_shipping_cost_to_delivery_country_eur", "cout_transport_estime"},
						{"shipping_fee_eur", "frais_port_encaisse"},
						{"inbound_transportation_cost_eur", "cout_transport_amont"},
						{"marketplace_fees_eur", "commissions_marketplace"}
					}),
					#"Jointure couts bloc5" = Table.NestedJoin(
						#"Colonnes renommees",
						{"id_commande"},
						stg_couts_bloc5_commande,
						{"order_id"},
						"bloc5",
						JoinKind.LeftOuter
					),
					#"Couts bloc5 developpes" = Table.ExpandTableColumn(
						#"Jointure couts bloc5",
						"bloc5",
						{"retours_remboursements", "couts_generiques"},
						{"retours_remboursements", "couts_generiques"}
					),
					#"Avec bloc5" = Table.ReplaceValue(
						#"Couts bloc5 developpes",
						null,
						0,
						Replacer.ReplaceValue,
						{"retours_remboursements", "couts_generiques"}
					),
					// Page 11 : pre-agreger les postes grain colis (evite duplication des lignes commande).
					#"Couts colis par commande" = Table.Group(
						Table.SelectColumns(fact_transport, {"order_id", "cout_transport_retenu", "duties_taxes_eur", "shipping_supply_cost_eur"}),
						{"order_id"},
						{
							{"cout_transport_retenu_cmd", each List.Sum(List.Transform([cout_transport_retenu], each if _ = null then 0 else _)), type number},
							{"duties_taxes_cmd", each List.Sum(List.Transform([duties_taxes_eur], each if _ = null then 0 else _)), type number},
							{"fournitures_cmd", each List.Sum(List.Transform([shipping_supply_cost_eur], each if _ = null then 0 else _)), type number}
						}
					),
					#"Jointure couts colis" = Table.NestedJoin(
						#"Avec bloc5",
						{"id_commande"},
						#"Couts colis par commande",
						{"order_id"},
						"colis_agg",
						JoinKind.LeftOuter
					),
					#"Couts colis developpes" = Table.ExpandTableColumn(
						#"Jointure couts colis",
						"colis_agg",
						{"cout_transport_retenu_cmd", "duties_taxes_cmd", "fournitures_cmd"},
						{"cout_transport_retenu_cmd", "duties_taxes_cmd", "fournitures_cmd"}
					),
					#"Couts colis a zero" = Table.ReplaceValue(
						#"Couts colis developpes",
						null,
						0,
						Replacer.ReplaceValue,
						{"cout_transport_retenu_cmd", "duties_taxes_cmd", "fournitures_cmd"}
					),
					// Canal poste basculant (meme regle que le prototype Python page 11).
					#"Canal bascule" = Table.AddColumn(
						#"Couts colis a zero",
						"canal_bascule",
						each
							let s = if [source] = null then "" else Text.Trim([source]) in
							if Text.StartsWith(s, "AMAZON") then "AMAZON"
							else if s = "WEBSITE" or s = "PRO_WEBSITE" or s = "CULTURA" or s = "RAKUTEN" or s = "FNAC" then s
							else "AUTRES",
						type text
					),
					#"CA HT net" = Table.AddColumn(
						#"Canal bascule",
						"ca_ht_net",
						each if [state] = "CANCELLED" then 0 else if [ca_ht] = null then 0 else [ca_ht],
						type number
					),
					#"Frais port net" = Table.AddColumn(
						#"CA HT net",
						"frais_port_net",
						each if [state] = "CANCELLED" then 0 else if [frais_port_encaisse] = null then 0 else [frais_port_encaisse],
						type number
					),
					#"Marge brute commande" = Table.AddColumn(
						#"Frais port net",
						"marge_brute_commande",
						each
							[ca_ht_net] + [frais_port_net]
							- (if [cout_achat] = null then 0 else [cout_achat])
							- (if [cout_transport_amont] = null then 0 else [cout_transport_amont])
							- [cout_transport_retenu_cmd]
							- [duties_taxes_cmd]
							- (if [commissions_marketplace] = null then 0 else [commissions_marketplace])
							- [fournitures_cmd]
							- (if [retours_remboursements] = null then 0 else [retours_remboursements])
							- (if [couts_generiques] = null then 0 else [couts_generiques]),
						type number
					),
					// Passe 1 : mediane du ratio poste/CA par canal, sur non-deficitaires a CA > 0.
					#"Ref mediane" = Table.SelectRows(#"Marge brute commande", each [marge_brute_commande] >= 0 and [ca_ht_net] > 0),
					#"Medianes canal" = Table.Group(
						#"Ref mediane",
						{"canal_bascule"},
						{
							{"med_r_achat", each List.Median(List.Transform(List.Zip({[cout_achat], [ca_ht_net]}), each (if _{0} = null then 0 else _{0}) / _{1})), type number},
							{"med_r_amont", each List.Median(List.Transform(List.Zip({[cout_transport_amont], [ca_ht_net]}), each (if _{0} = null then 0 else _{0}) / _{1})), type number},
							{"med_r_outbound", each List.Median(List.Transform(List.Zip({[cout_transport_retenu_cmd], [ca_ht_net]}), each _{0} / _{1})), type number},
							{"med_r_duties", each List.Median(List.Transform(List.Zip({[duties_taxes_cmd], [ca_ht_net]}), each _{0} / _{1})), type number},
							{"med_r_commissions", each List.Median(List.Transform(List.Zip({[commissions_marketplace], [ca_ht_net]}), each (if _{0} = null then 0 else _{0}) / _{1})), type number},
							{"med_r_fournitures", each List.Median(List.Transform(List.Zip({[fournitures_cmd], [ca_ht_net]}), each _{0} / _{1})), type number},
							{"med_r_retours", each List.Median(List.Transform(List.Zip({[retours_remboursements], [ca_ht_net]}), each (if _{0} = null then 0 else _{0}) / _{1})), type number},
							{"med_r_generiques", each List.Median(List.Transform(List.Zip({[couts_generiques], [ca_ht_net]}), each (if _{0} = null then 0 else _{0}) / _{1})), type number}
						}
					),
					#"Medianes buffer" = Table.Buffer(#"Medianes canal"),
					#"Jointure medianes" = Table.NestedJoin(
						#"Marge brute commande",
						{"canal_bascule"},
						#"Medianes buffer",
						{"canal_bascule"},
						"med",
						JoinKind.LeftOuter
					),
					#"Medianes developpees" = Table.ExpandTableColumn(
						#"Jointure medianes",
						"med",
						{"med_r_achat", "med_r_amont", "med_r_outbound", "med_r_duties", "med_r_commissions", "med_r_fournitures", "med_r_retours", "med_r_generiques"},
						{"med_r_achat", "med_r_amont", "med_r_outbound", "med_r_duties", "med_r_commissions", "med_r_fournitures", "med_r_retours", "med_r_generiques"}
					),
					// poste_basculant : colonne calculee DAX (cascade), lit les med_r_* produits ici.
					#"Tranche panier" = Table.AddColumn(
						#"Medianes developpees",
						"tranche_panier",
						each
							let p = if [ca_ht] = null then 0 else [ca_ht] in
							if p < 15 then "Under 15 EUR"
							else if p < 20 then "15 to 20 EUR"
							else if p < 30 then "20 to 30 EUR"
							else if p < 40 then "30 to 40 EUR"
							else if p < 70 then "40 to 70 EUR"
							else if p < 90 then "70 to 90 EUR"
							else if p < 200 then "90 to 200 EUR"
							else "200 EUR and above",
						type text
					),
					#"Tranche panier ordre" = Table.AddColumn(
						#"Tranche panier",
						"tranche_panier_ordre",
						each
							let t = [tranche_panier] in
							if t = "Under 15 EUR" then 1
							else if t = "15 to 20 EUR" then 2
							else if t = "20 to 30 EUR" then 3
							else if t = "30 to 40 EUR" then 4
							else if t = "40 to 70 EUR" then 5
							else if t = "70 to 90 EUR" then 6
							else if t = "90 to 200 EUR" then 7
							else 8,
						Int64.Type
					),
					#"Colonnes conservees" = Table.SelectColumns(#"Tranche panier ordre", {
						"id_commande", "origin_order_id", "state", "source", "type_commande", "code_pays", "currency",
						"ca_ht", "ca_ht_reconstruit", "frais_port_encaisse", "cout_achat", "cout_transport_estime",
						"cout_transport_amont", "commissions_marketplace",
						"retours_remboursements", "couts_generiques",
						"gross_profit_eur", "gross_margin", "contribution_profit_eur", "contribution_margin",
						"date_commande",
						"marge_brute_commande",
						"canal_bascule", "ca_ht_net",
						"cout_transport_retenu_cmd", "duties_taxes_cmd", "fournitures_cmd",
						"med_r_achat", "med_r_amont", "med_r_outbound", "med_r_duties",
						"med_r_commissions", "med_r_fournitures", "med_r_retours", "med_r_generiques",
						"tranche_panier", "tranche_panier_ordre"
					})
				in
					#"Colonnes conservees"

