/// Faits — lignes d'articles par commande (grain : un article physique / customer_order_item).
/// Source : stg_Commande_Items (customer_order_item) ⋈ customer_order_item_group (ISBN / prix).
/// Relié à fact_commandes par order_id. Alimente le nombre d'articles (COUNTROWS).
table fact_lignes
	lineageTag: 131fd8d8-579b-4f13-8a68-fe0b13ecbd52

	column id_article
		dataType: int64
		isHidden
		lineageTag: 0839c18c-cc35-4d53-b62a-5c823590f387
		summarizeBy: none
		sourceColumn: id_article

	column item_group_id
		dataType: int64
		isHidden
		lineageTag: a1b2c3d4-e5f6-7890-abcd-ef1234567890
		summarizeBy: none
		sourceColumn: item_group_id

	/// Clé étrangère vers fact_commandes[id_commande].
	column order_id
		dataType: int64
		lineageTag: 35bb21ee-6213-469e-ac04-72f957d1bd74
		summarizeBy: none
		sourceColumn: order_id

		changedProperty = IsHidden

	/// Dupliqué depuis le groupe (customer_order_item_group) — une valeur par article du même groupe.
	column isbn
		dataType: string
		lineageTag: 541183b9-2cab-4530-ad10-04f7d28afb94
		summarizeBy: none
		sourceColumn: isbn

		changedProperty = IsHidden

	/// Dupliqué depuis le groupe — conservé pour contrôle/audit uniquement, PAS utilisé dans [Nb Articles].
	column quantity_groupe
		dataType: int64
		formatString: #,##0
		lineageTag: e10b7d4e-d6a0-4680-90ec-dc59decb898e
		summarizeBy: sum
		sourceColumn: quantity_groupe

		changedProperty = IsHidden

	/// Dupliqué depuis le groupe (customer_order_item_group) — une valeur par article du même groupe.
	column list_price_eur
		dataType: double
		formatString: #,##0.00 €
		lineageTag: 1c058ce0-d590-45c5-a549-70fb4896270f
		summarizeBy: none
		sourceColumn: list_price_eur

		changedProperty = IsHidden

	/// Dupliqué depuis le groupe (customer_order_item_group) — une valeur par article du même groupe.
	column customer_price_per_item_eur
		dataType: double
		formatString: #,##0.00 €
		lineageTag: 28528d38-6aa6-4371-b63c-ffd0b98cb809
		summarizeBy: none
		sourceColumn: customer_price_per_item_eur

		changedProperty = IsHidden

	/// Dupliqué depuis le groupe (customer_order_item_group) — une valeur par article du même groupe.
	column group_type
		dataType: string
		lineageTag: dd7412c2-c668-46db-ae4a-86436f59146e
		summarizeBy: none
		sourceColumn: group_type

		changedProperty = IsHidden

	column internal_state
		dataType: string
		lineageTag: b2c3d4e5-f6a7-8901-bcde-f23456789012
		summarizeBy: none
		sourceColumn: internal_state

	column package_id
		dataType: int64
		lineageTag: c3d4e5f6-a7b8-9012-cdef-345678901234
		summarizeBy: none
		sourceColumn: package_id

	column product_cost_eur
		dataType: double
		formatString: #,##0.00 €
		lineageTag: d4e5f6a7-b8c9-0123-defa-456789012345
		summarizeBy: sum
		sourceColumn: product_cost_eur

	/// Proxy Bloc3 : package_id comme substitut du champ ETF/sous-statut annulation,
	/// absent des exports backend (visible uniquement en interface backoffice à l'unité).
	/// À valider avec Marc en fin de mission — voir docs/notes-techniques/limite-etf-annulation.md
	column statut_annulation_ligne =
			IF(
				[internal_state] <> "CANCELLED",
				"NON_ANNULE",
				IF(
					ISBLANK([package_id]),
					"ANNULE_AVANT_EXPEDITION",
					"ANNULE_APRES_EXPEDITION"
				)
			)
		dataType: string
		lineageTag: e5f6a7b8-c9d0-1234-efab-567890123456
		summarizeBy: none

	/// Langue du livre (ISBN) — proxy Bloc 7 Finance dashboard. À remplacer si le backend exporte langue_livre.
	column langue_livre
		dataType: string
		lineageTag: f1e2d3c4-b5a6-9780-1234-567890abcdef
		summarizeBy: none
		sourceColumn: langue_livre

	/// Canal Finance (Website B2C / B2B / Marketplaces / Arthaud / Autre) — dénormalisé depuis la commande.
	column canal_ligne
		dataType: string
		lineageTag: a9b8c7d6-e5f4-3210-fedc-ba9876543210
		summarizeBy: none
		sourceColumn: canal_ligne

	/// Légende graphe General View : canal × langue livre.
	column canal_langue
		dataType: string
		lineageTag: b0c1d2e3-f4a5-6789-abcd-ef0123456789
		summarizeBy: none
		sourceColumn: canal_langue

	partition fact_lignes = m
		mode: import
		source =
				let
					#"Articles types" = Table.SelectColumns(stg_Commande_Items, {
						"id", "order_id", "item_group_id", "internal_state", "package_id", "product_cost_eur"
					}),
					#"Groupes brut" = Csv.Document(File.Contents(LocalRootPath & "\Données_Backend\customer_order_item_group.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
					#"Groupes source" = Table.PromoteHeaders(#"Groupes brut", [PromoteAllScalars = true]),
					#"Groupes types" = Table.SelectColumns(
						Table.TransformColumnTypes(#"Groupes source", {
							{"id", Int64.Type},
							{"isbn", type text},
							{"quantity", Int64.Type},
							{"list_price_eur", type number},
							{"customer_price_per_item_eur", type number},
							{"group_type", type text}
						}, "en-US"),
						{"id", "isbn", "quantity", "list_price_eur", "customer_price_per_item_eur", "group_type"}
					),
					#"Jointure articles groupes" = Table.NestedJoin(
						#"Articles types",
						{"item_group_id"},
						#"Groupes types",
						{"id"},
						"groupe",
						JoinKind.LeftOuter
					),
					#"Colonnes groupe developpees" = Table.ExpandTableColumn(
						#"Jointure articles groupes",
						"groupe",
						{"isbn", "quantity", "list_price_eur", "customer_price_per_item_eur", "group_type"},
						{"isbn", "quantity_groupe", "list_price_eur", "customer_price_per_item_eur", "group_type"}
					),
					#"Colonnes renommees" = Table.RenameColumns(#"Colonnes groupe developpees", {{"id", "id_article"}}),
					#"Sources commande" = Table.SelectColumns(stg_customer_order, {"id", "source"}),
					#"Jointure source commande" = Table.NestedJoin(
						#"Colonnes renommees",
						{"order_id"},
						#"Sources commande",
						{"id"},
						"cmd",
						JoinKind.LeftOuter
					),
					#"Source developpee" = Table.ExpandTableColumn(#"Jointure source commande", "cmd", {"source"}, {"source"}),
					#"Canal ajoute" = Table.AddColumn(#"Source developpee", "canal_ligne", each
						let
							raw = if [source] = null then "" else Text.Upper(Text.Trim([source])),
							s = if raw = "" then "INCONNU" else raw
						in
							if s = "WEBSITE" then "Website B2C"
							else if s = "PRO_WEBSITE" then "Website B2B"
							else if Text.StartsWith(s, "AMAZON") or s = "CULTURA" or s = "RAKUTEN" or s = "FNAC" then "Marketplaces"
							else if s = "ARTHAUD" then "Librairie Arthaud"
							else "Autre",
						type text
					),
					#"Langue livre ajoutee" = Table.AddColumn(#"Canal ajoute", "langue_livre", each
						let
							raw = if [isbn] = null then "" else Text.Replace(Text.From([isbn]), "-", ""),
							s = Text.Trim(raw)
						in
							if Text.Length(s) < 4 then "Autre"
							else if Text.StartsWith(s, "9782") or Text.StartsWith(s, "97910") then "Français"
							else if Text.StartsWith(s, "9780") or Text.StartsWith(s, "9781") then "Anglais"
							else if Text.StartsWith(s, "9783") then "Allemand"
							else if Text.StartsWith(s, "97884") then "Espagnol"
							else if Text.StartsWith(s, "97888") then "Italien"
							else "Autre",
						type text
					),
					#"Canal langue ajoute" = Table.AddColumn(#"Langue livre ajoutee", "canal_langue", each [canal_ligne] & " · " & [langue_livre], type text),
					#"Colonnes conservees" = Table.SelectColumns(#"Canal langue ajoute", {
						"id_article", "order_id", "item_group_id", "isbn", "list_price_eur",
						"customer_price_per_item_eur", "group_type", "quantity_groupe",
						"internal_state", "package_id", "product_cost_eur",
						"langue_livre", "canal_ligne", "canal_langue"
					})
				in
					#"Colonnes conservees"

