/// Faits — commandes clients (grain : une ligne par commande).
/// Source locale : Données_Backend/customer_order.csv (File.Contents via stg_customer_order).
/// Clé : id_commande (customer_order.id). Porte le CA, les coûts backend et
/// la marge existante (gross_profit_eur) conservée comme référence de contrôle.
table fact_commandes
	lineageTag: 11fa5581-3c36-4afa-ae59-a9cc19e15f69

	column id_commande
		dataType: int64
		isHidden
		lineageTag: 463339a0-5b78-4230-a496-61ef20b8aca3
		summarizeBy: none
		sourceColumn: id_commande

	column origin_order_id
		dataType: string
		lineageTag: b5efc10c-9a0b-454a-962a-6e58acc360a1
		summarizeBy: none
		sourceColumn: origin_order_id

		changedProperty = IsHidden

	column state
		dataType: string
		lineageTag: d552aead-fcf3-4c76-852d-52f81f7ea027
		summarizeBy: none
		sourceColumn: state

		changedProperty = IsHidden

	column source
		dataType: string
		lineageTag: 196d52ee-a2ce-4dc7-98b2-827d28f8e4a8
		summarizeBy: none
		sourceColumn: source

		changedProperty = IsHidden

	/// Axe d'analyse "type de commande" — dérivé de customer_order.source
	/// (canal de vente : WEBSITE, AMAZON_FR, ...). Interprétation à valider avec Lireka.
	column type_commande
		dataType: string
		lineageTag: f217ab35-b208-4bf8-877a-7eac9a4cb025
		summarizeBy: none
		sourceColumn: type_commande

		changedProperty = IsHidden

	/// Code pays de livraison ISO 3166-1 alpha-2 (destination_country). "??" si absent.
	column code_pays
		dataType: string
		lineageTag: f7d25057-6a3d-4a16-a18c-9d7405a8190b
		summarizeBy: none
		sourceColumn: code_pays

		changedProperty = IsHidden

	column currency
		dataType: string
		lineageTag: 49714872-95db-44f0-867a-8ecf6044a06c
		summarizeBy: none
		sourceColumn: currency

		changedProperty = IsHidden

	/// Chiffre d'affaires HT en EUR (order_amount_eur).
	column ca_ht
		dataType: double
		formatString: #,##0.00 €
		lineageTag: da448a96-2d78-471b-a902-701f6b5826fc
		summarizeBy: sum
		sourceColumn: ca_ht

		changedProperty = IsHidden

	/// CA HT reconstruit en EUR (order_amount_eur natif ou order_amount_local / taux mensuel).
	/// Voir commentaire Power Query dans la partition et docs/notes-techniques/reconstruction-ca-marketplace.md.
	column ca_ht_reconstruit
		dataType: double
		formatString: #,##0.00 €
		lineageTag: e7f80912-a3b4-5678-9abc-def012345678
		summarizeBy: sum
		sourceColumn: ca_ht_reconstruit

		changedProperty = IsHidden

	/// Fix F-04 : frais de port encaissés auprès du client en EUR (shipping_fee_eur).
	/// Renommé shipping_fee_eur -> frais_port_encaisse pour exposer le poste
	/// "shipping revenue" de la formule Marc à la mesure [Frais Port Encaissés].
	column frais_port_encaisse
		dataType: double
		formatString: #,##0.00 €
		lineageTag: 52d273ed-6508-4932-bff1-838a5a742071
		summarizeBy: sum
		sourceColumn: frais_port_encaisse

		changedProperty = IsHidden

	/// Fix F-04 : coût de transport amont (inbound_transportation_cost_eur) — poste
	/// "inbound transportation costs" de la formule Marc.
	column cout_transport_amont
		dataType: double
		formatString: #,##0.00 €
		lineageTag: 1a2b3c4d-5e6f-4a7b-8c9d-0e1f2a3b4c5d
		summarizeBy: sum
		sourceColumn: cout_transport_amont

		changedProperty = IsHidden

	/// Fix F-04 : commissions marketplace (marketplace_fees_eur) — poste
	/// "marketplace commission fees (fixed and variable)" de la formule Marc.
	column commissions_marketplace
		dataType: double
		formatString: #,##0.00 €
		lineageTag: 2b3c4d5e-6f7a-4b8c-9d0e-1f2a3b4c5d6e
		summarizeBy: sum
		sourceColumn: commissions_marketplace

		changedProperty = IsHidden

	/// Bloc5 (dette technique) — retours et remboursements agrégés par commande
	/// (SUM returns_and_refunds_cost_eur depuis customer_order_item). Périmètre provisoire.
	column retours_remboursements
		dataType: double
		formatString: #,##0.00 €
		lineageTag: c6d7e8f9-a0b1-4234-c567-8901bcdef012
		summarizeBy: sum
		sourceColumn: retours_remboursements

		changedProperty = IsHidden

	/// Bloc5 (dette technique) — coûts génériques agrégés par commande
	/// (SUM generic_costs_eur depuis customer_order_item). Périmètre provisoire.
	column couts_generiques
		dataType: double
		formatString: #,##0.00 €
		lineageTag: d7e8f9a0-b1c2-4345-d678-9012cdef0123
		summarizeBy: sum
		sourceColumn: couts_generiques

		changedProperty = IsHidden

	/// Coût d'achat des livres en EUR (product_cost_eur).
	column cout_achat
		dataType: double
		formatString: #,##0.00 €
		lineageTag: 0303a735-7e7b-4bff-8814-6fd3cf44e57c
		summarizeBy: sum
		sourceColumn: cout_achat

		changedProperty = IsHidden

	/// Coût transport estimé par le backend (total_shipping_cost_to_delivery_country_eur).
	column cout_transport_estime
		dataType: double
		formatString: #,##0.00 €
		lineageTag: 79df602e-014e-4609-a7b7-a507fbd957bb
		summarizeBy: sum
		sourceColumn: cout_transport_estime

		changedProperty = IsHidden

	/// Marge brute calculée par le backend Lireka — RÉFÉRENCE de contrôle uniquement.
	column gross_profit_eur
		dataType: double
		formatString: #,##0.00 €
		lineageTag: f936cdd0-712e-4107-a083-08085058721b
		summarizeBy: sum
		sourceColumn: gross_profit_eur

		changedProperty = IsHidden

	column gross_margin
		dataType: double
		formatString: 0.0%
		lineageTag: 284dce96-d29d-47cc-aa2e-4efe3a4de945
		summarizeBy: none
		sourceColumn: gross_margin

		changedProperty = IsHidden

	column contribution_profit_eur
		dataType: double
		formatString: #,##0.00 €
		lineageTag: 3958fe58-b33f-4fae-9e18-9493fc0c905e
		summarizeBy: sum
		sourceColumn: contribution_profit_eur

		changedProperty = IsHidden

	column contribution_margin
		dataType: double
		formatString: 0.0%
		lineageTag: 423d5a02-6639-4ac1-bea1-21532a5f4993
		summarizeBy: none
		sourceColumn: contribution_margin

		changedProperty = IsHidden

	/// Date de la commande (origin_created tronqué au jour). Clé vers dim_date.
	column date_commande
		dataType: dateTime
		formatString: yyyy-MM-dd
		lineageTag: 420154ac-c0fc-48be-ba16-c422162d47db
		summarizeBy: none
		sourceColumn: date_commande

		changedProperty = IsHidden

		annotation UnderlyingDateTimeDataType = Date

	partition fact_commandes = m
		mode: import
		source =
				let
					// Fix F-04 : typage des postes de marge manquants (inbound + commissions marketplace)
					// avant de les exposer au modèle. shipping_fee_eur / duties / supplies déjà typés en amont.
					#"Types postes marge" = Table.TransformColumnTypes(stg_customer_order, {
						{"inbound_transportation_cost_eur", type number},
						{"marketplace_fees_eur", type number}
					}, "en-US"),
					#"Date commande ajoutee" = Table.AddColumn(#"Types postes marge", "date_commande", each try Date.FromText(Text.Start([origin_created], 10), [Format = "yyyy-MM-dd"]) otherwise null, type date),
					#"Annee mois ajoutee" = Table.AddColumn(
						#"Date commande ajoutee",
						"annee_mois",
						each if [date_commande] = null then null else Date.Year([date_commande]) * 100 + Date.Month([date_commande]),
						Int64.Type
					),
					// CA reconstruit marketplace (taux moyen mensuel).
					#"Jointure taux mensuel" = Table.NestedJoin(
						#"Annee mois ajoutee",
						{"currency", "annee_mois"},
						stg_taux_moyen_mensuel,
						{"devise", "annee_mois"},
						"taux",
						JoinKind.LeftOuter
					),
					#"Taux mensuel etendu" = Table.ExpandTableColumn(#"Jointure taux mensuel", "taux", {"taux_moyen_mensuel"}, {"taux_moyen_mensuel"}),
					#"CA eur reconstruit" = Table.AddColumn(
						#"Taux mensuel etendu",
						"order_amount_eur_reconstruit",
						each
							let
								eurNatif = [order_amount_eur],
								montantLocal = [order_amount_local],
								taux = [taux_moyen_mensuel]
							in
								if eurNatif <> null and eurNatif <> 0 then eurNatif
								else if montantLocal <> null and montantLocal <> 0 and taux <> null and taux <> 0 then montantLocal / taux
								else null,
						type nullable number
					),
					#"Code pays normalise" = Table.AddColumn(#"CA eur reconstruit", "code_pays", each if [destination_country] = null or Text.Trim([destination_country]) = "" then "??" else Text.Upper(Text.Trim([destination_country])), type text),
					#"Type commande derive" = Table.AddColumn(#"Code pays normalise", "type_commande", each if [source] = null or Text.Trim([source]) = "" then "INCONNU" else Text.Trim([source]), type text),
					#"Colonnes renommees" = Table.RenameColumns(#"Type commande derive", {
						{"id", "id_commande"},
						{"order_amount_eur", "ca_ht"},
						{"order_amount_eur_reconstruit", "ca_ht_reconstruit"},
						{"product_cost_eur", "cout_achat"},
						{"total_shipping_cost_to_delivery_country_eur", "cout_transport_estime"},
						{"shipping_fee_eur", "frais_port_encaisse"},
						{"inbound_transportation_cost_eur", "cout_transport_amont"},
						{"marketplace_fees_eur", "commissions_marketplace"}
					}),
					#"Jointure couts bloc5" = Table.NestedJoin(
						#"Colonnes renommees",
						{"id_commande"},
						stg_couts_bloc5_commande,
						{"order_id"},
						"bloc5",
						JoinKind.LeftOuter
					),
					#"Couts bloc5 developpes" = Table.ExpandTableColumn(
						#"Jointure couts bloc5",
						"bloc5",
						{"retours_remboursements", "couts_generiques"},
						{"retours_remboursements", "couts_generiques"}
					),
					#"Avec bloc5" = Table.ReplaceValue(
						#"Couts bloc5 developpes",
						null,
						0,
						Replacer.ReplaceValue,
						{"retours_remboursements", "couts_generiques"}
					),
					#"Colonnes conservees" = Table.SelectColumns(#"Avec bloc5", {
						"id_commande", "origin_order_id", "state", "source", "type_commande", "code_pays", "currency",
						"ca_ht", "ca_ht_reconstruit", "frais_port_encaisse", "cout_achat", "cout_transport_estime",
						"cout_transport_amont", "commissions_marketplace",
						"retours_remboursements", "couts_generiques",
						"gross_profit_eur", "gross_margin", "contribution_profit_eur", "contribution_margin",
						"date_commande"
					})
				in
					#"Colonnes conservees"

