/// Faits — factures transporteurs unifiées (récaps Colissimo + Chronopost).
/// Sources SharePoint (format français, séparateur ";", décimale virgule) :
/// Dashboards_transporteurs/COLISSIMO Dashboard PowerBI/2025 & 2026 *.csv
/// Dashboards_transporteurs/CHRONOPOST Dashboard PowerBI/2025 *.csv
/// Colissimo est un service La Poste (suivi 6A...). Sert au rapprochement
/// factures <-> colis via numero_suivi (contrôle du coût réel backend).
table fact_factures_transport
	lineageTag: 3e48232a-1883-4a3e-bf86-44d0d480d1fa

	/// Numéro de facture (Chronopost uniquement ; vide pour Colissimo).
	column numero_facture
		dataType: string
		lineageTag: 456a2c4f-83b7-417a-a21c-27b78d735243
		summarizeBy: none
		sourceColumn: numero_facture

		changedProperty = IsHidden

	/// Date de la facture (clé vers dim_date).
	column date_facture
		dataType: dateTime
		formatString: yyyy-MM-dd
		lineageTag: ae273671-c725-47cd-abaa-2bb0e89acd27
		summarizeBy: none
		sourceColumn: date_facture

		changedProperty = IsHidden

		annotation UnderlyingDateTimeDataType = Date

	/// Numéro de suivi nettoyé — clé de jointure vers fact_transport.
	column numero_suivi
		dataType: string
		lineageTag: 038ff088-2d9d-4271-b72a-e91eb4d07ab5
		summarizeBy: none
		sourceColumn: numero_suivi

		changedProperty = IsHidden

	/// Transporteur canonique (La Poste pour Colissimo, Chronopost).
	column transporteur
		dataType: string
		lineageTag: 4550186f-ae1e-4003-8ca0-6fe6f9300d5e
		summarizeBy: none
		sourceColumn: transporteur

		changedProperty = IsHidden

	column service
		dataType: string
		lineageTag: 10db3ac1-f9f1-4847-aa55-18b0d80f8724
		summarizeBy: none
		sourceColumn: service

		changedProperty = IsHidden

	/// Pays de destination (Colissimo : préfixe de la colonne Destination).
	column pays_destination
		dataType: string
		lineageTag: 899d1dc8-28bb-492c-be09-bb1be241d2c9
		summarizeBy: none
		sourceColumn: pays_destination

		changedProperty = IsHidden

	column poids
		dataType: double
		formatString: #,##0.000
		lineageTag: 1605cb0c-7a09-4959-9929-bbadb56a058a
		summarizeBy: sum
		sourceColumn: poids

		changedProperty = IsHidden

	/// Coût transport facturé HT en EUR (colonne TOTAL HT du récap).
	column cout_transport
		dataType: double
		formatString: #,##0.00 €
		lineageTag: 125e8180-2944-4f06-a00f-186548827da1
		summarizeBy: sum
		sourceColumn: cout_transport

		changedProperty = IsHidden

	column devise
		dataType: string
		lineageTag: cbbfc9cf-c110-481d-9dc7-c1eea172df42
		summarizeBy: none
		sourceColumn: devise

		changedProperty = IsHidden

	/// Commande rattachée (résolue par proximité de date, cf. partition).
	column order_id
		dataType: int64
		isHidden
		lineageTag: 7b1f0c2d-3e4a-4b5c-8d6e-9f0a1b2c3d4e
		summarizeBy: none
		sourceColumn: order_id

	/// Colis rattaché (clé vers fact_transport, résolu par proximité de date).
	column id_package
		dataType: int64
		isHidden
		lineageTag: 8c2a1d3e-4f5b-4c6d-9e7f-0a1b2c3d4e5f
		summarizeBy: none
		sourceColumn: id_package

	partition fact_factures_transport = m
		mode: import
		source =
				let
					// TEST ISOLATION R2 — true = table vide (skip refresh lourd). Remettre false pour réactiver.
					IsolationSkipR2 = true,
					Result =
						if IsolationSkipR2 then
							#table(
								type table [
									numero_facture = text,
									date_facture = date,
									numero_suivi = text,
									transporteur = text,
									service = text,
									pays_destination = text,
									poids = number,
									cout_transport = number,
									devise = text,
									order_id = Int64.Type,
									id_package = Int64.Type,
									nb_candidats_resolution = Int64.Type
								],
								{}
							)
						else
							let
								// Logique unifiée dans stg_factures_transport_resolu (résolution par date, sans
								// dépendance circulaire vers fact_transport — consommée aussi pour source_cout).
								#"Devise ajoutee" = Table.AddColumn(stg_factures_transport_resolu, "devise", each "EUR", type text)
							in
								#"Devise ajoutee"
				in
					Result

