/// Faits — colis / coûts de transport (grain : une ligne par colis).
/// Source locale : Données_Backend/package.csv (File.Contents).
/// cout_transport = shipping_cost_eur (estimation backend ou coût saisi).
/// Fix F-02 : cout_transport_facture = montant facturé rapproché ; cout_transport_retenu =
/// facturé si disponible sinon estimé (poste "outbound" de la marge).
/// Fix F-03 : source_cout : "facture_rapprochee" (facture Colissimo/Chronopost rapprochée dont
/// la VALEUR est portée dans cout_transport_retenu), "backend_seul" (backend sans facture —
/// Colis Privé, Postes Canada, autres), "aucun" (ni facture ni coût backend).
/// Le transporteur est inféré du numéro de suivi (aucune colonne transporteur en source).
table fact_transport
	lineageTag: b67fcf1f-7c50-495f-9b64-c93508b2f1cd

	column id_package
		dataType: int64
		isHidden
		lineageTag: c3eb4b36-c475-4ae6-a15e-e6bdded84245
		summarizeBy: none
		sourceColumn: id_package

	/// Clé étrangère vers fact_commandes[id_commande] (package.order_id).
	column order_id
		dataType: int64
		lineageTag: 31686b5d-6e9a-4d1b-9ecb-5345bdfd9759
		summarizeBy: none
		sourceColumn: order_id

		changedProperty = IsHidden

	/// Numéro de suivi nettoyé (tracking_id) — clé de jointure avec les factures.
	column numero_suivi
		dataType: string
		lineageTag: e3d4aa94-26ca-4d04-9222-63a310117597
		summarizeBy: none
		sourceColumn: numero_suivi

		changedProperty = IsHidden

	/// Transporteur normalisé via fnNormaliserTransporteur (inférence par motif).
	column transporteur
		dataType: string
		lineageTag: 0c555f96-e526-4c91-8b23-6ff714093994
		summarizeBy: none
		sourceColumn: transporteur

		changedProperty = IsHidden

	/// Poids du colis en kg (weight source en grammes / 1000).
	column poids_kg
		dataType: double
		formatString: #,##0.000
		lineageTag: 6a0acb3f-3b78-4f06-8f6b-08c2b8d1c786
		summarizeBy: sum
		sourceColumn: poids_kg

		changedProperty = IsHidden

	/// Coût transport ESTIMÉ backend en EUR (shipping_cost_eur). Conservé tel quel pour les
	/// mesures de contrôle (Écart Réel vs Facturé, Écart Coût...).
	column cout_transport
		dataType: double
		formatString: #,##0.00 €
		lineageTag: 05fe8b41-606c-4237-9215-86371029809f
		summarizeBy: sum
		sourceColumn: cout_transport

		changedProperty = IsHidden

	/// Fix F-02 : montant facturé par le transporteur, rapproché au colis (null si aucune facture).
	column cout_transport_facture
		dataType: double
		formatString: #,##0.00 €
		lineageTag: 3c4d5e6f-7a8b-4c9d-0e1f-2a3b4c5d6e7f
		summarizeBy: sum
		sourceColumn: cout_transport_facture

		changedProperty = IsHidden

	/// Fix F-02 : coût outbound RETENU pour la marge = facturé si disponible, sinon estimé backend.
	column cout_transport_retenu
		dataType: double
		formatString: #,##0.00 €
		lineageTag: 4d5e6f7a-8b9c-4d0e-1f2a-3b4c5d6e7f8a
		summarizeBy: sum
		sourceColumn: cout_transport_retenu

		changedProperty = IsHidden

	column shipping_supply_cost_eur
		dataType: double
		formatString: #,##0.00 €
		lineageTag: 35ba76db-bfc4-428f-854a-798998f08964
		summarizeBy: sum
		sourceColumn: shipping_supply_cost_eur

		changedProperty = IsHidden

	column duties_taxes_eur
		dataType: double
		formatString: #,##0.00 €
		lineageTag: 33e2a80a-97b0-4611-9cf7-91e8adcc60ac
		summarizeBy: sum
		sourceColumn: duties_taxes_eur

		changedProperty = IsHidden

	/// Fix F-03 : origine du coût transport : facture_rapprochee | backend_seul | aucun.
	column source_cout
		dataType: string
		lineageTag: a4b5c6d7-e8f9-4a0b-1c2d-3e4f5a6b7c8d
		summarizeBy: none
		sourceColumn: source_cout

	partition fact_transport = m
		mode: import
		source =
				let
					#"Types appliques" = stg_package,
					#"Transporteur infere" = Table.AddColumn(#"Types appliques", "transporteur", each fnNormaliserTransporteur([tracking_id]), type text),
					#"Poids en kg" = Table.AddColumn(#"Transporteur infere", "poids_kg", each [weight] / 1000, type number),
					#"Colonnes renommees" = Table.RenameColumns(#"Poids en kg", {
						{"id", "id_package"},
						{"shipping_cost_eur", "cout_transport"}
					}),
					// Agrégat ensembliste des coûts facture par colis (évite Sum row-by-row sur nid).
					#"Couts facture par colis" = Table.Group(
						Table.SelectRows(
							Table.SelectColumns(stg_factures_transport_resolu, {"id_package", "cout_transport"}),
							each [id_package] <> null
						),
						{"id_package"},
						{{"cout_transport_facture", each List.Sum(List.RemoveNulls([cout_transport])), type number}}
					),
					#"Jointure facture" = Table.ExpandTableColumn(
						Table.NestedJoin(
							#"Colonnes renommees",
							{"id_package"},
							#"Couts facture par colis",
							{"id_package"},
							"fact",
							JoinKind.LeftOuter
						),
						"fact",
						{"cout_transport_facture"},
						{"cout_transport_facture"}
					),
					#"Cout retenu ajoute" = Table.AddColumn(
						#"Jointure facture",
						"cout_transport_retenu",
						each if [cout_transport_facture] <> null then [cout_transport_facture] else [cout_transport],
						type nullable number
					),
					#"Source cout" = Table.AddColumn(
						#"Cout retenu ajoute",
						"source_cout",
						each
							if [cout_transport_facture] <> null then "facture_rapprochee"
							else if [cout_transport] = null or [cout_transport] = 0 then "aucun"
							else "backend_seul",
						type text
					),
					#"Colonnes conservees" = Table.SelectColumns(#"Source cout", {
						"id_package", "order_id", "numero_suivi", "transporteur",
						"poids_kg", "cout_transport", "cout_transport_facture", "cout_transport_retenu",
						"shipping_supply_cost_eur", "duties_taxes_eur", "source_cout"
					})
				in
					#"Colonnes conservees"

	annotation PBI_ResultType = Table

